### ISSUE TITLE
Blueprint for ironic image needs to be built

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#102]
As a SCS operator, I need to have the blueprint for an ironic image that is prepared for the use with disk encryption.

This includes the following tasks:

- [x] Define specs for image. Image can be used for control nodes.
- [x] Define initial parameters for setting up crypto in image (eg. keyfile for LUKS)
- [x] Create build manifest (and try out packer as well as openstack imagebuilder)
- [x] Documentation

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Set of specs have been defined
- [x] A build manifest exists
- [x] Image has been tested in an existing environment that supports disk encryption
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by matfechner** [comment]
@fkr https://github.com/osism/openstack-ironic-images/pull/39 
documentation will follow very soon

**Comment by matfechner** [comment]
@fkr https://github.com/osism/documentation/pull/409
