### ISSUE TITLE
Blog post on linting / QA initiative in ansible code @ osism

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#103]
Let's write a blogpost together with OSISM on their work to improve quality within the ansible code.
Assuring good quality is often something that is neglected - with the work that OSISM is doing as part of the R3 cycle important steps are done towards assuring a certain quality is continuously assured. this is important work.

The blog post should feature _why_ this is done and furthermore also give technical insights into what is being done.
 
I'm going to to do this together with @ra-rau.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] The blog post is published on scs.community
- [x] All acceptance criteria are met

**Comment by itrich** [comment]
This can be considered as done
