### ISSUE TITLE
Stale issues

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/issues#11]
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/95 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/96 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/97 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/98 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/99 ~~
~~ - [ ] https://github.com/SovereignCloudStack/issues/issues/5 ~~
~~ - [x] https://github.com/SovereignCloudStack/website/issues/203 ~~
~~ - [x] https://github.com/SovereignCloudStack/website/issues/202 ~~
~~ - [x] https://github.com/SovereignCloudStack/website/issues/201 ~~
~~ - [x] https://github.com/SovereignCloudStack/website/issues/199 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/29 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/10 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/39 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/34 ~~
~~ - [x] https://github.com/SovereignCloudStack/Docs/issues/33 ~~

SEE COMMENTS BELOW

**Comment by fkr** [comment]
Re-assign to me. I'll work through these within the next days in order to see what to bring to the table in next refinement meetings.
