### ISSUE TITLE
Fix what is found by ansible-lint in osism

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#117]
Since ansible-lint has been integrated into the osism ansible repositories (see https://github.com/SovereignCloudStack/issues/issues/104), it now finds items. These will be addressed within this story.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by garloff** [comment]
All reports from ansible-lint have been addressed.
Future: Which attribute checks should be active? Which standards do we want to enforce?
