### ISSUE TITLE
Configuration issue in deployment via OSISM in regard to Octavia 

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#118]
In environments deployed via OSISM that use DVR as layer-3 there are configurational issues in regard to octavia. These should be documented so that future deployments will not suffer from these problems.
In order to document these properly a proper assessment of the problem needs to be done.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Documentation has been updated to reflect that use of DVR is not supported
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by berendt** [comment]
Discuss: Wavestack dropped DVR. We should document that it is not recommended to use DVR at all.

**Comment by garloff** [comment]
Let's close this as soon as we have documented to not use DVR.

**Comment by fkr** [comment]
Updated definition of done to reflect this
