### ISSUE TITLE
[Feature Request] Issues that are moved to 'Done' should automatically be closed

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#120]
This came up in Team IaaS Call on 2022-07-20. When items are moved to done, they should automatically be closed.

**Comment by berendt** [comment]
Looks like some automation is possible: https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/configuring-automation-for-project-boards

**Comment by fkr** [comment]
heh, right now it is actually configured the other way around :)
"When issue is closed, move it to done" - which of course works, but is not natural to working with a Kanban board.

![Screenshot 2022-07-20 at 12 35 23](https://user-images.githubusercontent.com/51063/179962043-b0faf84a-0c89-4a3b-9496-720649d681a4.png)

**Comment by itrich** [comment]
This has been released by GitHub
