### ISSUE TITLE
Evaluate existing status page applications against the requirements

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#121]
We already evaluated the existing status page applications a while ago. With the requirements we collected in https://github.com/orgs/SovereignCloudStack/discussions/89 (as well as the there linked etherpad) it should be easy to match that against the existing status page application (doing also a x-ref with the SCS OSS Healthcheck).

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Consolidate requirements into a consistent doc
- [x] There is a documented matrix that matches the popular OSS status pages with the requirements
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by garloff** [comment]
Weak dependence on CloudMon/ApiMon.

**Comment by garloff** [comment]
Requirements are clear: See
https://github.com/orgs/SovereignCloudStack/discussions/89
and the linked etherpad [20220602-status-page-scs-session.pdf](https://github.com/SovereignCloudStack/issues/files/8822531/20220602-status-page-scs-session.pdf)

**Comment by garloff** [comment]
Needs more research on existing tools.
See https://github.com/ivbeg/awesome-status-pages
We may need to create a tender and pay for some development.

**Comment by garloff** [comment]
Next step: Create a matrix which evaluates the properties of existing tools against the requirements.
(Always consider our OSS-Healthcheck criteria as well: https://github.com/SovereignCloudStack/Docs/blob/main/Design-Docs/OSS-Health.md)

**Comment by joshmue** [comment]
While taking a further look at the requirements, I wondered how large the overlap between a status page and e.g. on-call notifications is.

The requirements already include the requirement to have a REST API to allow calls which are `i.e. submitting a health beacon every x seconds`, which effectively hints to implementing a "dead man's switch" monitoring. The same mechanism is implemented by providers like OpsGenie ("Heartbeats") to notify on-call engineers.

So: Is on-call infrastructure something that should be covered by SCS? And if yes, how integrated should it work with the status page? I doubt that implementing mechanisms like the "dead man's switch" is desired, so it would need to be highly integrated?

**Comment by fkr** [comment]
@joshmue we discussed this a while back (roughly a year ago) in the SIG Monitoring and came to the conclusion that most CSPs have a 'on-call alert routing system' in place. Which is why we made sure to document on how to hook alertmanager (which is what is currently used in the IaaS layer for collecting the alerts from prometheus) into existing on-call solutions.
Looking forward - especially with the container layer in mind - we can (and should) re-visit the topic of alerta as a way to aggregate alerts again.

However, I'd try to leave this out of the scope of the status page, since this will lead to bloating up the scope of the status page.

**Comment by joshmue** [comment]
Thanks for clarification!

I guess that the "dead man's switch" is a nice-to-have feature rather than a strict requirement, then.

**Comment by master-caster** [comment]
Research on several projects started to check if they fit the requirements.
Any comments on the requirements are appreciated. If you do have an App thats missing
on the list feel free to add.
You already know on of the Apps? Feel free to update :grin: 
I will track my efforts here.

|                                          | CachetHQ  | ClearStatus   | ciao  | cState  | Gatus | Issue Status |
|------------------------------------------|---|---|---|---|---|---|
| CSP VIEW                                 |   |   |   |   |   |   |
| small dependency tree                    | ❌ Composer | ✅ |   |   |   |   |
| easy themable                            | ✅ | ❌ |   |   |   |   |
| grouping (by location...)                | ✅ | ❌ |   |   |   |   |
| components definition ...
| ... local and global                     | ✅ | ❌ |   |   |   |   |
| ... easy flagging with new status        | ✅ | ✅ |   |   |   |   |
| ... push notification on update          | ✅ |   |   |   |   |   |
| ... updates with additional information  | ✅ | ✅ |   |   |   |   |
| API Support ...                              
| ... versioned                            | ✅ | ❌ |   |   |   |   |
| ... web ui for posting updates           | ✅ | ✅ |   |   |   |   |
| ... token based auth                     | ✅ | ✅ Auth managed by git provider   |   |   |   |   |
| manageable configuration                 | ❌ config depends on web server and initial install relies on env variables | ❌ based on hugo CMS |   |   |   |   |
| templating support                       | ✅ twig | ❌ Hugo itself uses GO template libraries |   |   |   |   |
| CUSTOMER VIEW                            |   |   |   |   |   |   |
| subscription support ...                 | ✅ | ❌ only by git provider |   |   |   |   |
| ... send by eMail                        | ✅ |   |   |   |   |   |
| ... watchdog support                     |   |   |   |   |   |   |
| trigger webhook support                  | ❌ needs cachet-monitor  |   |   |   |   |   |
| ADDITIONAL INFORMATION                   |   | basically a theme for hugo cms  |   |   |   |   |
| hidden components                        | ✅ |   |   |   |   |   |
| user management                          | ✅ |   |   |   |   |   |
| different output format on notification  | ❌ |   |   |   |   |   |
| external hosting                         | ✅ |   |   |   |   |   |
| project healthy                          | ❌ last commit 17 months   |   |   |   |   |   |
| documentation                            | ✅ API ❌ User Documentation   |   |   |   |   |   |
| git based                                | ❌ | ✅ |   |   |   |   |

**Comment by master-caster** [comment]
Since it may take forever search and find suitable applications i won't spend time for investigation on every single candidate.
If our list here is not sufficient you may found additional information here: https://github.com/ivbeg/awesome-status-pages

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/Docs/blob/main/Decisions/status-page-comparison.md
