### ISSUE TITLE
Evaluate hardware testbox from Tuxedo for Cloud in a Box

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#129]
Tuxedo shipped us - based on our requirements - a computer that could be suiteable for Cloud in a Box.
We have until August 2nd to evaluate this hardware.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] We know wether this hardware suffices or what needs to be adjusted to meet our needs
- [x] All acceptance criteria are met

**Comment by garloff** [comment]
Why two small(!) SATA disks in addition to two NVMe drives?
