### ISSUE TITLE
Cloud-in-a-Box needs an USB stick image installer

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#130]
As a User of cloud-in-a-box, I want to start the install process via an USB stick. Once the usb stick is booting everything else is done in an autmated way and once finished the cloud-in-a-box boots a complete scs featuring the iaas reference implementation as well as the container ref implementation. The box then is ready to be used as a SCS environment.

As the SCS project we want to have a CI pipeline that will have a USB stick image as a outcome that contains latest/greatest SCS installer. The image should work on arbitrary hardware, but at least on the cloud-in-a-box reference hardware (e.g. by manually testing every major release).

The boot process should acquire ip connectivity via autoconf and dhcp.

The USB stick image allows me to reset the cloud-in-a-box to a known state at any given time.
There is a repo at @osism that contains parts for this: https://github.com/osism/manager-installer

This might need to be refined to be sliced into more fine-grained user stories. This will be discussed in Team IaaS call on July 27th.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] There exists a ci pipeline that has a usb stick image as outcome
- [x] There exists a usb stick image that can be used to install cloud-in-a-box
- [x] The installation results in a deployed tested
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
https://github.com/osism/manager-installer can be used as a base for this.

**Comment by fkr** [comment]
manager-installer has been renamed to https://github.com/osism/node-image
via cloud init it will then be boostrapped testbed

**Comment by fkr** [comment]
@berendt will see who will be the sparring partner for writing further user stories.
