### ISSUE TITLE
Partnership regarding Cloud-in-a-box

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#131]
As an interest of such a device, I want to have a webshop link where I can simply order a well-defined device for cloud-in-a-box.

As a SCS partner organization, I want to have a device, that I can recommend to interested consumers. This lowers the bar to begin playing around with SCS (and its tooling). 

## Definition of Ready:

- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] A technology partner has been chosen upon on our criteria
- [ ] An interested party can order a device for cloud-in-a-box
- [ ] Joined presswork has been started
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by itrich** [comment]
Blocked by #143

**Comment by itrich** [comment]
Let's evaluate the current hardware we ordered and how well the discussed cloud-in-a-box image works on these machines before we proceed with finding a partner for ready-to-use hardware dispatchment.

**Comment by itrich** [comment]
I'd propose to wait until we have a CiaB image that can be meaningfully used and then start to evaluate the Tuxedo hardware with a typical workload again.

I'd furthermore propose to remove this issue from #116 and re-investigate this topic after R4.

**Comment by berendt** [comment]
The CiaB image is ready to use from our PoV. Please test and open issues for further required features. Documentation is in progress.
