### ISSUE TITLE
Blog post on NBDE - Clevis/Tang

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/issues#133]
* NBDE overview
* Clavis & Tang service overview
* implementation in OSISM
* configuration in OSISM
* deployment & use in OSISM

Input in https://input.osb-alliance.de/p/SCS-OSISM-Blog-NBDE.

Sample PR for the website repository: https://github.com/SovereignCloudStack/website/commit/27d0ca12492ab684914f028942ad1a94ec696302

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] The blog post is published on scs.community
- [ ] All acceptance criteria are met

**Comment by matfechner** [comment]
https://github.com/SovereignCloudStack/website/pull/372

**Comment by matfechner** [comment]
https://sovereigncloudstack.github.io/website/2022/08/18/osism-nbde-install/

**Comment by berendt** [comment]
Published: https://scs.community/de/2022/08/17/osism-nbde-install/
