### ISSUE TITLE
Test of the use of IPv6 for North-South traffic in OSISM

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/issues#151]
As an SCS operator, I want to offer IPv6 for customer north-south traffic (via a provider network, not floating IPs).
Investigate how to get this to work and ensure it's continuously tested.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by berendt** [comment]
/29 network requested.

**Comment by garloff** [comment]
/29 network is available now at OSISM.
Jens working on hardware setup (@Hetzner) and deployment of testbed with IPv6:
- yoga
- SGX
- IPv6
- Own AS needed?
=> not in scope for R3, maybe as TechPreview

**Comment by fkr** [comment]
https://review.opendev.org/c/openstack/neutron-dynamic-routing/+/891038

**Comment by fkr** [comment]
https://docs.openstack.org/neutron-dynamic-routing/latest/install/usecase-ipv6.html
