### ISSUE TITLE
Documentation of federated authentication

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#160]
As a SCS Operator, I need proper documentation for the federated authentication in order to set it up.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Setup has been documented within the OSISM documentation
- [ ] There is a documentation piece in Operational Docs @ SCS pointing to OSISM chapter
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by reqa** [comment]
related to https://github.com/SovereignCloudStack/issues/issues/96 ?

**Comment by fkr** [comment]
Docs are for now here: 

https://github.com/SovereignCloudStack/Docs/blob/main/Decisions/intra-SCS-federation-setup-description-for-osism-doc-operations.md

**Comment by fkr** [comment]
Discuss with @maxwolfs on how to integrate such documentation pieces into the SCS information architecture.

**Comment by fkr** [comment]
@reqa @JuanPTM please discuss with @maxwolfs for next weeks meeting.

**Comment by fkr** [comment]
There are useful pieces here that can serve as a good starting point: https://scs.community/2023/01/05/sig-iam-openstack-cli-with-federation/

**Comment by reqa** [comment]
As discussed with @maxwolfs , shall go into https://github.com/SovereignCloudStack/docs/tree/main/operations/iam

**Comment by fkr** [comment]
@maxwolfs We just discussed in the IAM Call that [this](https://github.com/SovereignCloudStack/standards/tree/main/Drafts/IAM-federation) actually belongs to the docs/ repository as well. Do you concur?

**Comment by reqa** [comment]
In https://github.com/SovereignCloudStack/issues/issues/160#issuecomment-1406693646 I was referring to two separate things:
1. The operations guide should at some later point be extended to explain the required procedure to configure and make use of OIDC federation. And then it probably makes sense there to reference the document that used to be in `Design-Docs/IAM-federation`.
2. `Design-Docs/IAM-federation` which now has been moved to [this](https://github.com/SovereignCloudStack/standards/tree/main/Drafts/IAM-federation) place.

AFAIU Felix is asking, if `Drafts/IAM-federation)` can be moved from `standards/Drafts/` to `docs/Design-Docs/`.

**Comment by fkr** [comment]
> AFAIU Felix is asking, if `Drafts/IAM-federation)` can be moved from `standards/Drafts/` to `docs/Design-Docs/`.

actually I meant moving to `docs/operations/iam` (https://github.com/SovereignCloudStack/docs/tree/main/operations/iam)

**Comment by reqa** [comment]
I'm not sure if this stuff is already suitable as documentation for "operations". It's more an architecture description which can be referenced later at other points. But then, I don't know about the docs concept.
