### ISSUE TITLE
Have better labels in Grafana Dashboards

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#162]
As a SCS Operator I would find it very helpful, if the Grafana Dashboards would not just display IPs but symbolic names instead.

Generate a Document within the Operational Docs which outlines how to use overlay files for prometheus (detail out deep merge from prometheus.yml.d for custom subscrapes) and show example prometheus.yml to overule the generation of kolla default scrape jobs (IP based) with our desired form of scrape (fqdn based) 
this is possible thanks to OSISM rolling out /etc/hosts and the prometheus-server container mounting this file - no dns server needed.

Operational Docs:

https://github.com/SovereignCloudStack/Docs/tree/main/Operational-Docs

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by linwalth** [comment]
fqdn based scraping could be implemented by using inventory_hostname var instead of the construct the prometheus.yml template uses to extract the IP endpoint.

**Comment by fkr** [comment]
thanks @linwalth. will close the issue.
