### ISSUE TITLE
Decide on Database solution for managing persistent data

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#173]
The api server for the status page will need to have some persistence to store incidents and component status. 

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by joshmue** [comment]
DB options (anything distributed):

  - rqlite
     - (For Go) is not usable via generic database/sql or gorm, but has its own client library
     - (For Rust) is not usable via generic sqlx or diesel, but has its own client library
     - (For RoR) is not supported by ActiveRecord
  - etcd
     - KV Store, non-relational
  - dapr (leave it to operator which DB to use)
     - while underlying DB may be relational, dapr API is not (KV DB/Document DB)
  - cockroachdb
     - Postgres API compatible
  - TiDB
     - MySQL API compatible
  - MongoDB/Cassandra/Scylla

**Comment by joshmue** [comment]
For now, going with Postgres/CockroachDB.
