### ISSUE TITLE
Extend api server to allow setting component status

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#175]
Extend api server to allow setting component status via http request.
This should either be POST or PATCH - PATCH seems the most viable RESTy way.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Status Page api server accepts http requests to update component status
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by joshmue** [comment]
As discussed in #177,
> Component conditions are not manually set, but derived from the lifecycle of an incident.
So, this issue is actually an subset of #177 Closing.
