### ISSUE TITLE
Create simple webfrontend that displays the components and incidents

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#178]
Create simple webfrontend that displays the components and incidents with pagination (#223).

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] A webpage is displaying the data that comes from the status page api server
- [x] Components are visible on this webpage
- [x] Incidents are visible on this webpage
- [x] As a user I can browse the history of incidents
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by joshmue** [comment]
Started implementation on https://github.com/joshmue/scs-status-page-web

**Comment by jschoone** [comment]
Hi @joshmue, is this still in Doing?

**Comment by joshmue** [comment]
I guess that it can be considered done already, actually. Closing.
