### ISSUE TITLE
Evaluate wether fluentd is optimal from the viewpoint of a SCS operator

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#18]
As a SCS operator, I want to evaluate wether the resource consumption of fluentd is acceptable or wether something like vector is serving my purpose better.

Epic: #17 

Possible alternatives: fluentbit, vector

## Open Question

- [ ] Precise definition of 'too much ressource usage'
- [ ] Does limiting fluentd solve the issue?
- [ ] Do we really need an alternative or did we just not understand fluentd properly?
- [ ] Does it make sense to add an alternative instead of replacing fluentd
- [ ] Where is fluentd present? What is the scope of fluentd - how do we handle layers above IaaS?

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
As a comment: It is possible to limit individual services in Kolla in their resources. This helps to limit certain services that consume too much resources during runtime.

```
fluentd_dimensions: "{{ default_container_dimensions }}"
```

By default, no limits are set.

**Comment by master-caster** [comment]
How about promtail combined with Loki? That combination is capable to scrape and serve the logs in familiar way 
you already know from prometheus metrics. Log can than be filtered within grafana UI to fit your needs.
