### ISSUE TITLE
Document design decisions for Status Page application

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#180]
As the SCS Community, I want to be able to understand the design decisions that were taken on the path to the status page application.
These design decisions need to be properly documented.

This documentation could be a set of ADRs accompanied by diagrams etc.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] A set of design documents exists
- [x] A person that has not been part of the status page application development group has read the design documents and understood the decisions
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by master-caster** [comment]
I created a first draft for our decision to create a new application to fulfill our requirements on this.
As @fkr proposed this may be a set of ADRs that will also cover the applications design documentation
that is currently under development.

**Comment by master-caster** [comment]
URL to draft: https://github.com/master-caster/Docs/blob/main/Decisions/scs-0011-v1-status-page-create-decision.md

**Comment by fkr** [comment]
@master-caster is waiting for feedback.
@fkr to review until EOW CW2.

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/standards/pull/191 will be discussed in todays OPS Call

**Comment by fkr** [comment]
Next round, should be finalized in next sprint

**Comment by fkr** [comment]
asked @jschoone to review the PR, since he fullfills the requirement "a person that has not been part" and can say, wether the items we outlined in the document are actually understandable.
