### ISSUE TITLE
Documentation and best practices for fluentd configuration as overlays.

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#19]
As a SCS operator I expect documentation and best practice example on how to configure the overlays to point fluentd to an external aggegrator.

Epic: #17 

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
Where would be the right place to document this?

We have a section on Fluentd in our OSISM documentation in the Operations chapter.

There it would fit well for the Fluentd inside OSISM.

**Comment by fkr** [comment]
@berendt this is a very valid question. Initially I thought "just like with alertmanager, in the Operational Docs of SCS" (see: https://github.com/SovereignCloudStack/Docs/blob/main/Operational-Docs/integrating-alertmanager.md). HOWEVER - maybe those alertmanager examples *actually* should have gone into the osism documentation. So imho we're still on the search for a good place on best practice documentation in order to not have it redundant and also provide the most value (in this case I'd actually say, the OSISM documentation is the place where it creates the most value).
