### ISSUE TITLE
User Stories for extending keystone to support a manager role need to be written

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#206]
As the SCS developers in order to outline our work on keystone to support a manager role, we need to have proper user stories.
These need to be written.

@matfechner can assist with that.

## Links to relevant upstream information:
-   manager role:
    - https://review.opendev.org/c/openstack/keystone-specs/+/818603
    - https://review.opendev.org/c/openstack/keystone/+/822601
-   service role (maybe a related RBAC enhancement in this context):
    - https://review.opendev.org/c/openstack/keystone-specs/+/818616
 
## Definition of Done:

- [ ] User stories that guide our way towards getting the required roles implemented upstream 
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
Good item to discuss with our contacts within keystone team.

**Comment by reqa** [comment]
* https://github.com/SovereignCloudStack/issues/issues/184
* https://github.com/SovereignCloudStack/issues/issues/383
* https://github.com/SovereignCloudStack/issues/issues/384
* https://github.com/SovereignCloudStack/issues/issues/385
