### ISSUE TITLE
Research OICD identity federation with v3oidcpassword

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#209]
Research into [keystoneauth source code]() to find out if openstack --v3oidcpassword is the right way to go to achieve OIDC Identity Federation.

## Definition of Done:

- [x] This research is successful, if we know wether to base our work on v3oidcpassword or not => Result: No it's not, we decided to go with OAuth 2.0 Device Authorization Flow instead.
- [ ] All acceptance criteria are met
- [ ] Documentation has been updated

**Comment by reqa** [comment]
Result: No it's not, we decided to go with OAuth 2.0 Device Authorization Flow instead.
