### ISSUE TITLE
Supported k8s versions

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#219]
As an SCS cluster user, I want to be sure to have a consistent minimal set of k8s versions available across all SCS-compliant KaaS offerings.
(As SCS KaaS operator, I want to understand what k8s versions I need to offer to comply.)

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
After definition it has to be implemented/integrated in https://github.com/osism/openstack-image-manager/blob/main/etc/images/kubernetes.yml and https://github.com/osism/k8s-capi-images/blob/main/src/update-extra-vars.py.

**Comment by garloff** [comment]
Decision from 2022-11-28 discussion:
* Must provide latest minor version (minor acc. to semver style) no later than 4 mon after release
* Must provide latest patch version no later than a week after release
  - Should be faster for critical CVEs (CVSS >= 8)
  - Should be tested

**Comment by garloff** [comment]
TODO: Write ADR

**Comment by garloff** [comment]
Open question: Should we recommend a "beta" channel, where newer minor versions or newer patch versions can be made available prior to them being fully qualified?
Application operations teams may want to understand what changes they need to perform and start testing before the official availability of the latest k8s version. (Of course final qualification will need to be done after the operator provides the latest version with official support.)

**Comment by garloff** [comment]
Does not need to standardized:
* Providers can still do it
* Cutting edge customers might tend to deploy capi themselves and thus don't depend on a standardized way to get early access ...

**Comment by ajfriesen** [comment]
@garloff 

I tried to find the right ADR place. Is it this repo and folder?
https://github.com/SovereignCloudStack/Docs/tree/main/Decisions

And shall I take this example as a draft?
https://github.com/SovereignCloudStack/Docs/pull/170/files

**Comment by garloff** [comment]
Decisions is the right place, yes.
The existing ADRs (e.g. the SSD one from PR Docs/#150), the template from Docs/#169 or the draft from DOcs/#170) are all good examples.

**Comment by garloff** [comment]
See https://github.com/SovereignCloudStack/standards/pull/184
