### ISSUE TITLE
Discussion on whether or not to backport OVN exporter 'locally'

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#22]
Once the OVN exporter has been merged upstream, we need to discuss on whether or not to backport it locally (for example, within OSIMS) to have it available, *until* it comes with the OpenStack release where it has been merged.

See: #21

**Comment by fkr** [comment]
1) it must be merged upstream onto main 
2) only *if* upstream will not accept a backport, a local backport is adviseable
3) is the feature a blocking requirement?
4) is a local backport simple enough - if *not* this is a strong argument against a local backport

a) where do we document this decision? -> contributor guide (open issue)
b) present in weekly as well as scs-tech@

**Comment by fkr** [comment]
We will postpone the discussion of a local backport of the OVN exporter until #67 is done.

**Comment by garloff** [comment]
Plan is to not use a locally built image in production, but we can build images for development, test, ... purposes of course.
