### ISSUE TITLE
Initial stubs for testing status-page application needed

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#222]
As the SCS project we want to make sure that ci/cd is thought about and integrated early in the development cycle.
The mvp-0 of the status page needs some stubs for the testing.

Some kind of unit tests ("unit" being small parts of code handling inputs and outputs) or behaviour tests (using the API via HTTP) should be implemented.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Initial set of tests exists
- [x] The initial set serve as a building block to add further tests as development continues
- [x] Initial set of tests are hooked into zuul
- [ ] Changes have been reviewed
- [x] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by joshuai96** [comment]
Tests are set up and implemented in the status-page-api server. Test code is still under review.
