### ISSUE TITLE
Write ADR on the status page api

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#237]
As the SCS project we want to write a standard for the status page API.
This should be a very lean document that:

- contains a pointer to the ADR on the decisions that were taken for the development
- contains a pointer to the OpenAPI spec

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by bitkeks** [comment]
In Ops call [2024-02-08](https://input.scs.community/2024-scs-team-ops?both#2024-02-08) we discussed this issue and were wondering if it can be re-activated. There seems to be content 

However, Standard SCS-0402-v1 (https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0402-v1-status-page-openapi-spec-decision.md) currently only seems to contain the decisions regarding OpenAPI, not the Status Page API itself.

@fkr should we revisit this issue?

**Comment by fkr** [comment]
While I actually thought it would add value (this is why I created the issue back in 2022), I doubt it adds any real value. The design considerations can be pulled from the OpenAPI spec and honestly there is no need to bloat this up.
I'd say: just close.
