### ISSUE TITLE
Install zuul head node

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#243]
Based on the infos / input from OSISM, the zuul head node needs to be installed.
This includes:

* getting OSISM collections up and running
* before taking it live, do first steps with a test github organization
* make sure it works with our github organization

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] There exists ansible code (playbook(s) to deploy a fully functional Zuul Head Node
- [x] The developed playbooks roll out a fine-grained configuration of the node pools along the requirements present through the OSISM zuul as well as coming from upstream OpenStack
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [x] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by master-caster** [comment]
Status Update.
Installing the necessary Zuul components is no problem due to the ansible role created by osism.
Right now the zuul_web container is complaining about the zuul_config repository configuration.
This is what I try to fix currently.

**Comment by master-caster** [comment]
Any Job other than the NOOP job will utilize nodepool. Nodepool uses dib for image building an that is the current
stage I'm working on.

Building an image is currently failing.

**Comment by master-caster** [comment]
Building the image is working now. But nodepool will fail to communicate with the created an uploaded VM.

**Comment by o-otte** [comment]
@master-caster will prepare a short presentation on using Zuul for a lightning-talk slot

**Comment by master-caster** [comment]
For now zuul head node is up and running.
Their will be some modification in terms of resource usage.
How many parallel Task etc. may run.

Next step in this context is to clean up the playbook and recreate
the head node. After this is done we can focus on pipelines and jobs.

**Comment by master-caster** [comment]
Redeploy seem to work fine. 
You find all necessary code on: https://github.com/SovereignCloudStack/zuul

There is now a basic zuul deployment that can be archived pretty easily in terms of zuul :sweat_smile: 

That means that the code is not completed yet since we will most likely update something to
fit our new requirements.

**Comment by fkr** [comment]
with this, I've now opened a PR for adding the 'zuul' repo to the list of our maintained repos, so that the usual branch protections etc. apply. Please review: https://github.com/SovereignCloudStack/github-manager/pull/120 @master-caster
