### ISSUE TITLE
Make sure the status page related repos are in github manager

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#256]
We need to fix  that I created various status page related repos by hand and switch them to the github-manager.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All manually created status page repos are handled via github-manager
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by itrich** [comment]
This is related to https://github.com/SovereignCloudStack/github-manager/issues/45

These surely won't be the last repositories that will be created without using the github-manager.
