### ISSUE TITLE
mod_oauth2 module availability in SCS

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#26]
Epic: #25 

The mod_outh2 module will be available in Debian Bookworm. 
Once available in bookworm, we need to have a container for us.

The proper way needs to be discussed.

**Comment by reqa** [comment]
I've contacted the maintainers of https://packages.debian.org/source/bookworm/libapache2-mod-auth-openidc about this and one of them encouraged packaging a source package and offered to sponsor the upload. So I guess we should create a Debian source package along the lines of `libapache2-mod-auth-openidc` (maybe `libapache2-mod-auth-oauth2`) and diskuss the details of uploading. As a first step, we should compare `libapache2-mod-auth-openidc` to the upstream package offered by `zomartzone`, to get an understanding of the "Debian way" for packaging this.

**Comment by reqa** [comment]
Uploaded an initial Debian source package to https://github.com/reqa/libapache2-mod-oauth2 and asked the Debian maintainer of mod-auth-openidc for feedback.

**Comment by reqa** [comment]
It's now in bookworm: https://packages.debian.org/search?keywords=libapache2-mod-oauth2

**Comment by fkr** [comment]
Nothing more we can do.
