### ISSUE TITLE
Push OpenStack CLI plugin for "Device Authorizazion Grant" for upstream adoption

### ISSUE THREAD

**Issue by reqa** [SovereignCloudStack/issues#261]
The "Device Authorization Grant" plugin for OpenStack Keystoneauth created via #233 shall be submitted upstream.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Patch submitted upstream for review https://review.opendev.org/c/openstack/keystoneauth/+/869876
- [x] Patch is communicated for review upstream (e.g. via keystone meeting)
- [x] Patch is accepted upstream
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
This is probably the best place to discuss wether or not we should anticipate a backport to zed.
@berendt @osfrickler what is your take on that?
Does it make sense to pursue this upstream?

**Comment by osfrickler** [comment]
We already submitted the backport yesterday https://review.opendev.org/c/openstack/keystoneauth/+/876809. I'm not sure whether it is compatible with stable branch rules, though, will have to wait for feedback from upstream reviewers.

**Comment by fkr** [comment]
awesome. thanks @osfrickler!

**Comment by fkr** [comment]
@reqa take into PTG (ask kristi beforehand wether that makes sense and if it should be added to the agenda)

**Comment by garloff** [comment]
Merged upstream.
