### ISSUE TITLE
Container registry: Create overview of needed and desirable features and map OSS solutions against it.

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#263]
As Open Community, we want to be transparent how we take technology decisions.
In this case, we want to ensure we have transparency over the decision for a container registry that we ship with our reference implementation. 
(Note: The existence of a container registry will likely be relevant for standardization, but we may not need to go beyond that, as the plain container functionality is fairly straight-forward and standardized, AFAIU. We might however want to standardize further functionality later?)
Let's create an overview over the feature set of open source [1] container registry options and map out requirements (and nice-to-haves) against it to have a well-documented decision.
Note: We have some preexisting work on harbor, which may give it a bonus point or two ... but it certainly does not imply that a final decision for it has been taken.
[1] Open Source health check: 
Tasks:
- [x] Create overview over OSS solutions and their capabilities (@chess-knight): https://github.com/SovereignCloudStack/standards/pull/212
- [ ] Distill requirements from project proposal (and previous discussions) (@garloff)

**Comment by jschoone** [comment]
Hi @garloff, are you still on the task `Distill requirements from project proposal (and previous discussions)`?
