### ISSUE TITLE
Research: Health Monitor for LB with OVN provider

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#268]
As a k8s ingress user, I want to see real client IPs in the ingress.
To make this work without proxy-protocol workarounds, we must ensure 
- [ ] that we use externalTrafficPolicy: local (otherwise we see the kube-proxy forwarded source IPs)
- [ ] have a health-monitor enabled (otherwise the nodes without the nginx will receive and drop traffic)
- [ ] have a loadbalancer that does preserve the client IPs (by working on layer 3 or similar ways to steer the flows)

The octavia load balancer implemented by the OVN provider does preserve the client IPs nicely, see #251 
It has a number of advantages (lightweight, quick to provision), but the documentation states that it does not support a healthmonitor. OVN itself has the notion of healthchecks, which should allow an efficient way to  implement some health monitor functionality. It does not seem to be wired up yet, though.

**Comment by garloff** [comment]
There are patches ...
https://opendev.org/openstack/ovn-octavia-provider/commit/8bbd8f1b62d7811433079bff8ce940fbdd041a0c

**Comment by garloff** [comment]
It was merged on 2021-07-23 with commit b25bc5773486bdb6e67d30dede34fbabf81606ec (tag: 1.1.0)
So we should have a working health monitor -- I need to check why it appeared not to do anything (never set a member to offline and the pool to degraded) in my testing.

**Comment by garloff** [comment]
In gx-scs, the health monitor can be enabled with an ovn provided LB (and pool), yet it seems to be ineffective.

**Comment by garloff** [comment]
In a Cloud-in-a-Box test setup, I can see the health monitor on OVN provider loadbalancer detect that members are unhealthy:
```json
                "pools": [                                                                                                              
                    {                                                                                                                   
                        "id": "a22a8bf8-1cf5-4185-8d17-81f48b4d353b",                                                                   
                        "name": "test-pool",                                                                                            
                        "provisioning_status": "ACTIVE",                                                                                
                        "operating_status": "DEGRADED",
                        "health_monitor": {
                            "id": "a3761d9a-a9b2-4d73-9086-129b7535dbdc",
                            "name": "",
                            "type": "TCP",
                            "provisioning_status": "ACTIVE",
                            "operating_status": "ONLINE"
                        },
                        "members": [
                            {
                                "id": "90dd100e-ed9d-4c1b-8877-afc985bff5dd",
                                "name": "test4",
                                "operating_status": "ERROR",
                                "provisioning_status": "ACTIVE",
                                "address": "192.168.224.119",
                                "protocol_port": 80
                            },
                            {
                                "id": "a909f074-1953-4be5-85f3-06f3cf9000bf",
                                "name": "test3",
                                "operating_status": "ONLINE",
                                "provisioning_status": "ACTIVE",
                                "address": "192.168.224.196",
                                "protocol_port": 80
                            },
                            {
                                "id": "ab73eab8-15e4-4862-a82b-51fd4f61e7b8",
                                "name": "test1",
                                "operating_status": "ONLINE",
                                "provisioning_status": "ACTIVE",
                                "address": "192.168.224.84",
                                "protocol_port": 80
                            },
                            {
                                "id": "fb37ae21-cc4e-41fa-9696-f0e386f45e1f",
                                "name": "test2",
                                "operating_status": "ERROR",
                                "provisioning_status": "ACTIVE",
                                "address": "192.168.224.79",
                                "protocol_port": 80
                            }
                        ]
                    }
                ]
```
which is exactly what I was hoping for.

Two remaining problems:
* In the openstack-health-monitor tests on gx-scs, this did not happen. This might be due to a different topology w.r.t. subnets used by LB VIP and members or due to differences in the cloud setup.
* The ERROR operating status of the members did not cause the LB to no longer distribute requests to the ERROR'ed members -- oops! So in the above example, 50% of the requests fail due to 2/4 ERROR'ed members.

**Comment by garloff** [comment]
On gxscs, the ERROR operating status is not only detected, but also working: The ERROR'ed members  no longer get requests.

**Comment by garloff** [comment]
Setting the subnet of the members correctly causes the loadbalancer's health-monitor on gx-scs to correctly detect the ERROR status of the members.

**Comment by garloff** [comment]
When connecting to the LB's VIP address directly, all requests succeed, i.e. no requests are forwarded to the backend members with ERROR operating status.
However, when connecting to the floating IP associated with the LB's VIP, this is *not* the case.

This is very very confusing and probably caused by some magic in OVN.
Speculation based on superficial OVN knowledge:
* OVN does the floating IP attachment by adding flows directly for the floating IP
* The ERROR'ed operating status causes OVN to disable the flows for the VIP, but not for the associated floating IP

**Comment by garloff** [comment]
OK, seems this is a known (and not addressed issue):
https://bugs.launchpad.net/neutron/+bug/1956035

**Comment by fkr** [comment]
@matfechner will take this to tonights octavia meeting.

**Comment by garloff** [comment]
> @garloff  @fkr  the octavia ovn provider is a neutron project. the discussion should happend there, i will bring it to this next neutron meeting

Thanks, @matfechner, very much appreciated!

**Comment by fkr** [comment]
thanks @matfechner

**Comment by garloff** [comment]
Another problem:
* The ON LB's health-monitor only supports TCP, not HTTP. This makes perfect sense as the LB also only support L3/L4 load-balancing.
* That's not what OCCM wants though.

So, here's what I would like to see happening next:
- Bug https://bugs.launchpad.net/neutron/+bug/1956035 really makes the OVN LB only half as useful as it could be. Fixing this should not be particularly hard and I would prioritize this. Any progress?
- For OVN HTTP health-monitor, we could wait for this to happen upstream or maybe contribute to it.
- Alternatively, we could contribute a patch to OCCM to allow for a cloud.conf option and service annotation to setting the health-monitor to TCP mode instead of HTTP.

**Comment by garloff** [comment]
Take this into PTG (@matfechner)

**Comment by garloff** [comment]
See https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/325#issuecomment-1487519544:
The health-mon not working for the floating IPs should be fixed in zed since early March, see
commit https://review.opendev.org/c/openstack/ovn-octavia-provider/+/873860
(commit https://review.opendev.org/c/openstack/ovn-octavia-provider/+/875595 against Zed)
which fixes https://bugs.launchpad.net/neutron/+bug/1997418/
which appears to be a duplicate of https://bugs.launchpad.net/neutron/+bug/1956035.

**Comment by fkr** [comment]
https://github.com/osism/issues/issues/499 - @garloff is still able to reproduce this on gx-scs.

**Comment by fkr** [comment]
To be finalized and checked until EOW

**Comment by matfechner** [comment]
i can reproduce it, too. I've investigated the octavia container and the needed patch is included, i guess that the tcp -health monitor itself could have an issue or a bug, that should discuss upstream

**Comment by artificial-intelligence** [comment]
why wasn't bug https://bugs.launchpad.net/neutron/+bug/1997418 reopened if it still can be reproduced? did anybody contact upstream maintainers over different channels about this problem?

**Comment by fkr** [comment]
@artificial-intelligence will do a backport for Zed so that we have a chance of getting that into 5.3.0

**Comment by artificial-intelligence** [comment]
backports:

antelope: https://review.opendev.org/c/openstack/ovn-octavia-provider/+/888544

zed: https://review.opendev.org/c/openstack/ovn-octavia-provider/+/888545

yoga: https://review.opendev.org/c/openstack/ovn-octavia-provider/+/888546

all not yet merged.

**Comment by artificial-intelligence** [comment]
all upstream patches mentioned above have been merged.

**Comment by berendt** [comment]
Will be part of OSISM 5.3.0.
