### ISSUE TITLE
Gnocchi and ceilometer enabled and present in testbed

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#271]
As a SCS Developer, I need to have gnocchi and ceilometer in the testbed and configured in a way that it works. Data arrives via ceilometer in gnocchi and can be seen in gnocchi.
Expectation is that timings from currently running instances can be seen.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] A freshly deployed testbed carries gnocchi and ceilometer
- [x] gnocchi and ceilometer work as expected
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
https://github.com/osism/testbed/pull/1503

**Comment by fkr** [comment]
@cah-link please see https://docs.osism.tech/configuration/environments/openstack.html for adding the docs bit.
@berendt will add a section to the release notes @ osism to cover testbed related items.

**Comment by horazont** [comment]
Concrete TODO:

- [ ] Add ceilometer section to the source of the openstack.html
- [ ] Provide information on how to turn it on/off
