### ISSUE TITLE
Playbooks for generating usage on testbed

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#272]
In order to work with gnocchi and ceilometer there must be utilization on the testbed to actually have data to gather.
For this we should have a set of playbooks / terraform files to work with.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] There is a set of playbooks / terraform files to use in order to utilize a testbed
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
Can we use https://github.com/osism/openstack-simple-stress for this? This generates instances all the time and deletes them again. Volumes can also be attached, I think.

We have also built this into the latest manager service as a tool that you can use with the OSISM CLI.

**Comment by fkr** [comment]
not needed anymore
