### ISSUE TITLE
Definition of objects and datasets for metrics collection

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#273]
As the SCS project we need to align of the objects that are part of the metrics collection in the reference implementation.
There needs to be a way for CSPs to easily add/remove objects from being accounted for.
We need to assure that the datasets that are stored suffice for our purpose.

These aspects need to be clearly documented and where a decision making process was being taken an ADR should exist.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] It is documented how CSPs add / remove objects from being collected and available through docs.scs.community
- [ ] ~It has been evaluated and assured that the datasets we store and how we store them suffice our purpose~
- [ ]  ~There exists consent in the Team IaaS on the openstack objects we account for~
- [x] There exists a config file for metric-to-api-sender to define which metrics are sent to api
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by cah-link** [comment]
https://github.com/SovereignCloudStack/docs/pull/45
PR for metric collection setting documentation
