### ISSUE TITLE
Visual overview of metrics collection architecture

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#277]
There should be a visual overview in the sense of an architectural diagram as as well as possibly a sequence diagram.

The architecture diagram should provide an overview of the involved components.

The sequence diagram should show how an exemplary billing event is handled from initial generation until usage is stored in gnocchi as well as shipping it to the api. 

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] There exists an architectural overview
- [x] There exists a sequence diagram
- [x] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
@cah-link should talk to @maxwolfs in order to make sure this is placed in the proper place from the start.

**Comment by cah-link** [comment]
the workflow diagram:
https://github.com/cloudandheat/odoo_openstack_metering/blob/main/docs/VP13workflow.png

the sequence diagram:
https://github.com/cloudandheat/odoo_openstack_metering/blob/main/docs/VP13_sequence.png
