### ISSUE TITLE
Integrate SCS compliance checker in zuul

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#279]
As a first use-case for the SCS zuul we should integrate the SCS compliance checker.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] There should be a zuul job that runs the SCS compliance checker against gx-scs
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
docker run -it --env OS_CLOUD=gxscs-capi -v ~/.config/openstack😕root/.config/openstack:ro 
ghcr.io/sovereigncloudstack/scs-compliance-check:main

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/standards/tree/main/Tests

**Comment by itrich** [comment]
This has been achieved for GitHub.

**Comment by o-otte** [comment]
We pushed this issue to the upcoming sprint due to the public holiday on thursday, because there is no sprint planning on that day.

**Comment by fkr** [comment]
@o-otte we have a sprint planning tomorrow (we moved it from Thursday to tomorrow) ;)
However, despite that, I think, it is fine to pull stuff into doing nevertheless! Thanks for being proactive!

**Comment by master-caster** [comment]
Trying to port some checks to zuul jobs i tried to create some workflow sufficient to work with.
Let's use the example for flavor name checks: https://github.com/SovereignCloudStack/standards/blob/main/Tests/iaas/flavor-naming/flavor-names-openstack.py

This script can be called with various arguments to access information of the desired cloud.
As Zuuls CI/CD nature it may run on pre-defined actions or on a time based interval.

So how would you apply the information that zuul should go ahead and check a given cloud for compliance?
At least Zuul will need access to that cloud by parameters often specified in a cloud.yaml.

Right now you have to clone the repo or run a container for the compliance check to happen. (or do i miss something?)

**Comment by master-caster** [comment]
For testing purposes i used to create a PR that will trigger a job that will fetch all available flavors from the given
cloud.

This seem to work. A small step for SCS a huge leap for me :grin:
