### ISSUE TITLE
Extend status page OpenAPI spec to include write operations

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#281]
The status page openapi spec needs to be extended to include the write operations for CUD operations.
This should follow the rest(-less) paradigm and work with proper http methods.

* partially to be retrieved from existing API server (https://github.com/sovereigncloudstack/status-page-api)
* leave out the auth features of openapi, document need for auth somewhere else

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] The openapi spec includes the operations needed to create, update and delete ressources.
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by JoshuaI96** [comment]
The write operations are now defined.
