### ISSUE TITLE
Using Let's encrypt for SCS Zuul

### ISSUE THREAD

**Issue by master-caster** [SovereignCloudStack/issues#292]
As part of the Zuul installation used by SCS we want to create an ansible playbook that will provide
a ready to use Zuul. That means we should cover all certificate requirements if possible. In this context the first
step is to consider how to provide Let's encrypt certificates for Zuul.

Using OSISM service ansible role we need to provide two public endpoints that are defined as
1. zuul.scs.community
2. zuul-log.scs.community
For these names Let's encrypt certificates are requested.

For now there is only one requirement defined.
* fetching and certificate renewal has to be as much automated as possible
Some soft targets:
* @osfrickler stated out that we may consider HA from now on as a future capability
* Using HTTP-01 challenge method (may conflict with HA)
* avoid daisy chaining reverse proxys

**Comment by fkr** [comment]
We should really solve this @master-caster - the cert is expired currently.
What is needed for you to make sure this is done via LE?

**Comment by master-caster** [comment]
In cooperation with jnull we were investigating the current state and what can be done to archive acme http challenge to 
work properly. 

Since, by default, the ansible zuul role, that we use for deployment, will bind to the necessary ports the most promising solutions will implement some changes to the ansible rule itself.

**Comment by master-caster** [comment]
Right now it is sufficient to run 
`certbot certonly --webroot -d zuul.scs.community -d zuul-logs.scs.community --staple-ocsp -m zapiec@gonicus.de --agree-tos -v`

That will renew the certificate and place the files in the correct place.
After fetching the new certificate `zuul_log_server` needs to be restart/reloaded otherwise the apache won't 
use the new certificate.

**Comment by master-caster** [comment]
opened a pull request: https://github.com/osism/ansible-collection-services/pull/1126

this is meant to be a starting point for discussion. Maybe we can use an OPS meeting session for this?

**Comment by okautz** [comment]
@PixelPhantomX and @o-otte are working on finalizing PR https://github.com/SovereignCloudStack/zuul/pull/10 to have a new basis of deploying the SCS Zuul instance. The PR will also include the possibility to setup a identical Zuul dev instance to preview changes to the deployment to minimize the impact on the productive system.
