### ISSUE TITLE
Use Authorization Code flow with PKCE in Keycloak OIDC federation

### ISSUE THREAD

**Issue by reqa** [SovereignCloudStack/issues#293]
As a user of SCS, I want Keystone OIDC federation to use "Authorization Code flow with PKCE" instead of "Implicit Grant" so that I follow security best practice for OpenID Connect.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Put `OIDCPKCEMethod plain` into the `wsgi-keystone.conf`. Maybe there are also even better settings
- [x] We should also disable the `Implicit Flow` in the `keystone` client config in Keycloak
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
We set this to R4, it is not really likely we will make this for R4, since this is change in OSISM and OSISM has been frozen for their 5.0.0 release (which is the base for R4). TBD.

**Comment by matfechner** [comment]
This seems to be an Upstream Issue, we should bring this disscussion to the PTG

**Comment by fkr** [comment]
Not really sure, wether I'm the only one but maybe it can be elaborated _what_ exactly should be addressed _where_ upstream?
Defaults coming from kolla-ansible? Or defaults coming from keystone?

**Comment by reqa** [comment]
> Not really sure, wether I'm the only one but maybe it can be elaborated _what_ exactly should be addressed _where_ upstream? Defaults coming from kolla-ansible? Or defaults coming from keystone?

The `OIDCResponseType "id_token"` is used both in kolla-ansible as well as in the keystone documentation:
* https://github.com/openstack/kolla-ansible/blob/f5b3f9d22b270026ab0f91ced737934e8c4d3b50/ansible/roles/keystone/defaults/main.yml#L243
* https://docs.openstack.org/keystone/latest/admin/federation/configure_federation.html#configure-mod-auth-openidc
* https://docs.openstack.org/keystone/latest/admin/federation/configure_federation.html#configuring-multiple-identity-providers

From out experiments with Zitadel and Keycloak we think that `OIDCResponseType "code"` and activating PKCE would be better.

**Comment by fkr** [comment]
What I understood:

- we can easily change this behaviour within OSISM (from @berendt 's comment). This is something we should do imho.
- however, it is worth taking this upstream to have more secure defaults (from @reqa 's comment). This can (and should) be done during PTG (as @matfechner suggested).

**Comment by JuanPTM** [comment]
The behavior on OSISM should already be changed (https://github.com/osism/testbed/pull/1549) due to this PR from last week.

**Comment by berendt** [comment]
@JuanPTM This changes the behavior in the testbed, yes. But not the general behavior of OSISM. For that, the changes have to be made in osism/ansible-defaults.

**Comment by reqa** [comment]
Just to clarify:
* There are different "flavors" of the implicit grant, depending on the configuration of the `response_type`.
* [Why you should stop using the OAuth implicit grant](https://medium.com/@torsten_lodderstedt/why-you-should-stop-using-the-oauth-implicit-grant-2436ced1c926) talks about response_type `token`.
* Fortunately we are not talking here about that most problematic flow, where the access token can be leaked. Instead the upstream recommended `wsgi-keycloak.conf` configuration uses `id_token`. 
* According to [OpenID-Connect core](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitCallback) specification, the `response parameters are returned in the Redirection URI fragment value`, i.e. by appending `#id_token=` to the redirect URI.
* The [section on implicit grant in the current draft of the OAuth 2.0 Security Best Current Practice](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-2.1.2) primarily refers to `token`, not `id_token`. 
* From this info and following e.g. [this report](https://salt.security/blog/traveling-with-oauth-account-takeover-on-booking-com) I think that the `id_token` can be leaked in our case. I guess the implications are less severe than with `token` included in the `response_type`.
* In contrast, at the time of writing, the [OpenID Connect Implicit Client Implementer's Guide 1.0 - draft 25](https://openid.net/specs/openid-connect-implicit-1_0.html) doesn't mention any security notice.
* The use case for implicit grant are Web clients (SPA) which can cannot keep a client secret.
* I don't think that Keystone SSO Federation is limited to using implicit grant, so we should not use it if we can avoid it.
* The successful WebSSO (horizon) test with Authorization Code Flow with PKCE with Ztadel (and later reproduced with Keycloak) shows that we have at least one alternative. There may be even better ones.

**Comment by mffap** [comment]
Maybe as additional consideration: Besides the [best practices recommendation for OAuth 2.0](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-22#name-implicit-grant) to drop Implicit Grant, the [OAuth 2.1 standard will remove Implicit grant](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#name-removal-of-the-oauth-20-imp) completely.

**Comment by garloff** [comment]
Switching over from implicit grant to PKCE, which needs additional enablement in keystone.
Followup patch (to the work from #261) needed there.
Switch in testbed already performed. (Workaround in place for now until keystone patch exists and is merged.)

**Comment by reqa** [comment]
I've submitted https://review.opendev.org/c/openstack/keystoneauth/+/883852 for upstream review.

**Comment by reqa** [comment]
My patch to support PKCE with Device Authorization Grant in OpenStack has been merged upstream.

**Comment by reqa** [comment]
Not sure if the changes that have been applied to the testbed for this also need to be reflected in https://github.com/osism/cfg-cookiecutter . Maybe @matfechner knows?

**Comment by garloff** [comment]
Update from 2023-08-23:
* We need the code change that was accepted for upstream master (will be in bobcat). Possibly backported by upstream or by OSISM?
* We need a config change for OSISM testbed and cfg-* repositories.

**Comment by reqa** [comment]
FYI: Just a technical clarification: Recently I stumbled upon this again, and found that this has both, a security aspect (for the security of the IdP) on the one hand and an interoperability aspect on the other hand.

1. Security:
The kolla-ansible upstream uses `keystone_federation_oidc_response_type: "id_token"` which, according to the [OpenID Connect Core 1.0 spec](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest) is also a type of `Implicit Flow`, but still different than the `Implicit Grant` defined by  `response_type: token`, which issues an `access_token` directly from the authorization endpoint (rather than an `id_token`). -- So, there is a difference here between OAuth 2.0 `Implicit Grant` (which is deprecated) and the `Implicit Flow` mentioned in the OpenID Connect spec.

Accordingly, the document linked above by @mffap

> [the [OAuth 2.1 standard will remove Implicit grant](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-08#name-removal-of-the-oauth-20-imp) completely.

explicitly says about the OAuth 2.1:
```
Removal of response_type=token does not have an effect on other extension response types returning other artifacts from the authorization endpoint, for example, response_type=id_token defined by [[OpenID](https://openid.net/specs/openid-connect-core-1_0.html)].
```

So these are different things. Yet, as already elaborated in my [clarification note above](https://github.com/SovereignCloudStack/issues/issues/293#issuecomment-1476150417), I think it's good to use the authorization code instead of implicit flows.

2. Interoperability
But there is also an interoperability aspect to it with regards to the choice of IdP. As [this overview by authlete](https://darutk.medium.com/diagrams-of-all-the-openid-connect-flows-6968e3990660) points out:
```
Be careful when you select an authorization server because there exist implementations which support response_type=code only but claim they support OpenID Connect.
```

**Comment by garloff** [comment]
Done.
