### ISSUE TITLE
Flavor manager should be reference in scs-0100-v2-flavor-naming

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#296]
Now that we have a way to manage flavors easily on SCS compliant clouds, the tool should be reference from [scs-0100-v2-flavor-naming.md](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v2-flavor-naming.md).

## Definition of Done:

- [x] scs-0100-v2 has a reference to the flavor manager
- [x] Release Notes have been updated

**Comment by tibeer** [comment]
Relates SovereignCloudStack/release-notes#9

**Comment by tibeer** [comment]
The release notes will remain in a draft state until the release is cut. The flavor naming standards now have a reference to the flavor manager.
