### ISSUE TITLE
ADR: Is a Standard or Recommendation of Monitoring Requirements for a CSP needed?

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#301]
As a SCS Developers, I want to have verifiable standards so that Users can rely on CSP fulfilling those standards.

We do not know yet, if a standard is needed for what a a CSP should or must fulfil with respect to their observability of managed Kubernetes offerings.

The outcome should be an ADR on if a standard, recommendation, or nothing at all is needed.

The aspect is separate on how an managed observability offering could look like.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] ADR is written
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by okautz** [comment]
We have this ADR in form of https://github.com/SovereignCloudStack/standards/pull/394, hence closing this for now.
