### ISSUE TITLE
Automatic Setup of Exporters for Observability of managed K8s clusters

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#302]
As a CSP, I want to observe the state of the clusters running on my infrastructure so that I have all necessary information on fixing broken clusters.

Therefore exporter tools need to be installed on every cluster that is provisioned.

Those tool will include: tbd

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by chess-knight** [comment]
This issue is resolved, see the merged PRs above
