### ISSUE TITLE
Observability data from KaaS Clusters is scraped

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#303]
As a SCP I want the scrape the observability data of all managed Kubernetes Clusters to ensure stability of Clusters.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Time Series Database exists
- [ ] Exporters are scraped automatically
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by chess-knight** [comment]
This issue is resolved, see the merged PRs above
