### ISSUE TITLE
There exist Dashboards for KaaS Cluster Health

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#304]
As a CSP, I want see the health of KaaS Clusters so that I can easily see if there is an incident and can act fast to mitigate an issue.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] There exist a set of Dashboards for KaaS Clusters
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by michal-gubricky** [comment]
Issue resolved, addressed in related pull requests.
