### ISSUE TITLE
Alerts are defined on the KaaS Clusters metrics

### ISSUE THREAD

**Issue by okautz** [SovereignCloudStack/issues#305]
As a CSP, I want to be informed if there are any issues with KaaS Clusters so that I can mitigate possible issues and ensure working KaaS offerings.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Alerts are defined and Alerting mechanism is in place
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by chess-knight** [comment]
This issue is resolved, see the merged PRs above

**Comment by chess-knight** [comment]
This issue is resolved, see the merged PRs above
