### ISSUE TITLE
Document setup of customer facing disk encryption with barbican

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#31]
As a SCS Operator, I need documentation on how to setup the customer facing disk encryption with barbican holding the keys the customer brings.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by berendt** [comment]
Please check if https://github.com/osism/documentation/pull/369 is sufficient.
