### ISSUE TITLE
Investigate UCS user management for local users

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#315]
As an IaaS/KaaS customer, I want to have the ability to manage users locally on a cloud (and not need to bring an own IdP). 

This could be done using the user management from keycloak.
Or we reuse the user management capabilities of UCS (keeping the users in LDAP and exposing via SAML and OIDC).
We need to investigate what the best way is.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by reqa** [comment]
There are at least two options here:

1. As UCS itself offers SAML and  OpenID-Connect via Keycloak, it can be used as IAM that the SCS builtin IdP (also Keycloak currently) federates out to. That could be used for "local" users too, if we run the UCS IAM stack within UCS
2. As UCS itself offers LDAP, it can be used directly as backend e.g. for Keycloak "User Federation". This is how the "UCS Keycloak App" itself does it, to consume and offer user identities for SSO

Currently UCS is an enterprise Linux distribution focused on IAM. While it has been practically demonstrated that it can be run as a (strictly non-cloud-native) container (https://github.com/univention/ucs-appliance-container), it still is a full blown VM. We could run it (either VM or container) in an SCS deployment.

OTOH Univention is currently working on a more cloud-native approach of turning the IAM stack into containerized services that are ready for deployment on K8S. That's WIP.

**Comment by garloff** [comment]
Using the Web-UI from keycloak to create local users (needed when jump starting new customers or when customers come without their own IdP) seems the better option for now.
In other words: UCS does not bring enough advantages to justify the currently relatively high complexity of deploying and managing it.
