### ISSUE TITLE
Teach ceilometer about publishing data from polling

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#320]
For the metrics collection for billing purposes we want to have a reliable data source and discovered that the publish process in ceilometer is called on event notifications but not on polling.

If rabbitMQ is not working properly we miss events like the resize of a cinder volume and gnocchi never gets updated on that.

We expected also a publishing mechanism to update the gnocchi resource by polling but that did not work. After some research we didn't found a call of the publisher process from polling and a triaged bugreport from [2017](https://bugs.launchpad.net/ceilometer/+bug/1730961) where "publish straight from polling agents" was suggested.

## Definition of Ready:

- [x] Have an answer to: Why ceilometer publishes only on events but not on polling? 
- [x] Know wether there is a reason for this design decision?
- [ ] ~Know how the proper upstream way of addressing is~

## Definition of Done:

- [x] Ceilometer is able to create resources in gnocchi by polling openstack services
- [ ] ~Patch has been submitted to upstream~ - no patch needed
- [x] PR, which teaches ceilometer about the publishing to http endpoint, in OSISM has been merged 
- [ ] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by cah-link** [comment]
https://github.com/osism/testbed/pull/1704 PR for publishing to http endpoint

**Comment by garloff** [comment]
2023-08-09: polling still WIP

**Comment by cah-link** [comment]
https://github.com/osism/testbed/pull/1719
PR for pushing Events directly

**Comment by fkr** [comment]
PR has been merged.
