### ISSUE TITLE
Performance Benchmarks for customer facing disk encryption

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#33]
As a SCS Operator, I'd like to have some numbers to understand the impact of customer facing disk encryption.

## Definition of a benchmark

- [x] Underlying specs are documented
- [x] Benchmarks are reproduceable
- [ ] Tools used are documented
- [ ] Easily comparable

TKperf came as a suggestion that offers the possiblity to compare several benchmark runs (and which works with fio underneath)

## Where to store information regarding that

- the OSISM documentation is targeted at the SCS Operator. As such it should carry the information that is relevant for the SCS operator. This includes the definition of the benchmark as well as the infos on how to benchmark this in the environment of the SCS operator.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] https://github.com/SovereignCloudStack/issues/issues/83
- [x] https://github.com/SovereignCloudStack/issues/issues/97
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by matfechner** [comment]
The Performance messure results:
Raw: 502 MB/s
Luks: 408 MB/s

but the result is only a moment entry. i think the limiter is ceph cluster

**Comment by fkr** [comment]
This story is too large. Needs to be refined and split in smaller items.

**Comment by fkr** [comment]
Does LUKS have impact on ceph features?

**Comment by fkr** [comment]
FIO scenarios need to be written (https://github.com/SovereignCloudStack/issues/issues/83) and then documented how to run them so the operator can derive the numbers from the benchmarks.

**Comment by maliblatt** [comment]
As discussed I have attached our results from some benchmarks that we have made on our prod1 platform with encrypted volumes:
[ceph_encr.pdf](https://github.com/SovereignCloudStack/issues/files/8804960/ceph_encr.pdf)

**Comment by maliblatt** [comment]
To have a possibility to compare here are our results with the fio tests on unencrypted volumes:
[ceph_unencr.pdf](https://github.com/SovereignCloudStack/issues/files/8812314/ceph_unencr.pdf)

**Comment by fkr** [comment]
Blocked because of hardware issues.
