### ISSUE TITLE
Aptly container has been created

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/issues#334]
As a scs developer operator, I want to have a solution, that can ship the code / application in a way, that is not reliant on specific system specifications.

## Definition of Ready:

- [x] User Story is small enough to be finished within one release cycle
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] Container-ize aptly
- [x] Create a wrapper script that handles nearly all tasks automatically
  - [x] initial setup
  - [x] periodic updates
- [x] Create a config file schema

**Comment by tibeer** [comment]
@garloff @mbuechse Current status: I run the aptly commands as python subprocesses:

```python3
def runner(command: str) -> None:
    logger.info(command)
    process = subprocess.Popen(
        command,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        shell=True
    )
    while True:
        if process.poll() is not None:
            logger.info("PROCESS FINISHED")
            break
        else:
            time.sleep(5)
                logger.info("still working ...")
```

Unfortunately `shell=True` is required for my use-cases, since I also abuse this method for gpg key imports (which require a pipe...).
Now to the steps to reproduce:
1. Add mirrors like this `aptly mirror create mirror_000000 "https://packagecloud.io/netdata/netdata-edge/ubuntu jammy main"`
2. Perform `aptly mirror update mirror_000000`
3. Watch it getting stuck, depending on the mirror size. Small mirrors like the one described is updated in under one minute. Larger mirrors like `http://de.archive.ubuntu.com/ubuntu jammy main restricted universe multiverse` take about 45min to update. After roughly one minute, the update subprocess get's stuck infinitely with 0 CPU usage, 2,5 RAM usage und still not flagged as a Zombie process.

**Comment by tibeer** [comment]
Absolutely awesome! I ditched the `PIPE` and decided to trow the output directly to `sys.stdout`. As far as things are going right now, this seems to work. So no log file unfortunately, but things are looking good :)

**Comment by mbuechse** [comment]
Be advised that this is kind of a quick fix. You can always divert the subprocess' stdout and stderr into files (which you later append to your log if anything fishy happened), or you could use aforementioned `communicate` in your loop to read the pipes at regular intervals so they don't congest.

**Comment by tibeer** [comment]
Communicate is not possible, as the process aptly itself buffers the messages, so communicate would only get "all" messages once done. I decided to use stdout, as these processes are running in a kubernetes pod, streaming the output as container logs. Files would not make much sense (I think), since this container is packaed in a cronjob ressource in kubernetes and discarded once finished.

**Comment by mbuechse** [comment]
Sorry, I don't mean to insist (I have no stakes here), but for the sake of completeness: even if `aptly` buffers all messages, it might be possible to use `communicate` after all -- it wouldn't return anything until `aptly` finishes, and then it would be a matter of reading the pipe while aptly is writing to it. Of course, the 5 s wait should only be done if `communicate` doesn't return anything.

**Comment by tibeer** [comment]
Yes, it would. I just liked the idea to be able to see an actual output. The current mirroring of one upstream mirror takes about 45min, so I expect the whole mirroring process to take about 24h or so ^^

**Comment by mbuechse** [comment]
I think you would get both things -- capture output as well as give status updates -- like so:

```python
    while True:
        try:
            stdout_data, stderr_data = process.communicate(timeout=5)
        except TimeoutExpired:
            logger.info("still working ...")
        else:
            break
    logger.info("PROCESS FINISHED")
```

However, it might actually not be as good an idea because
> The data read is buffered in memory, so do not use this method if the data size is large or unlimited.

And I don't have a fix for that handy. Anyway, it's all just a side note.

**Comment by tibeer** [comment]
Still thanks a lot for this valuable input :) Maybe I find another solution in the future which is more elegant.

**Comment by garloff** [comment]
Writing the output to a log file (which can be incrementally read and displayed) may be an option.
The communicate() thing OTOH should work as well AFAICS.

**Comment by tibeer** [comment]
Completed.
