### ISSUE TITLE
Helm chart for deployments has been created

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/issues#335]
As a scs cloud operator, I want to have a solution, that offers me an easy to use deployment solution.

## Definition of Ready:

- [x] User Story is small enough to be finished within one release cycle
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] Test helm chart
- [x] Prevent scaling
- [x] Make sure gpg1 and data volumes are persistent

**Comment by tibeer** [comment]
Completed.

**Comment by fkr** [comment]
@tibeer where are the helm charts?
