### ISSUE TITLE
Better document certification development/election process

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/issues#343]
Note: This issue originates from a discussion (and subsequent action item) in the [2023-06-01 meeting](https://input.scs.community/2023-scs-sig-standardization?view#2023-06-01) of SIG Standardization/Certification (minutes not yet transferred):
> Write an article for the docs page summarizing the certification process for the wider audience.

# Background
IMO, there are two areas in which documentation could be improved.

1. I got confused by the coexisting versioning schemes for (a) individual standards on the one hand (as documented in [scs-0001](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0001-v1-sovereign-cloud-standards.md)) and (b) sets of standards on the other hand (as documented in [scs-0003](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0003-v1-sovereign-cloud-standards-yaml.md)). Thanks to clarification in the above-mentioned meeting, I realized that (a) is only relevant for internal purposes and not authoritative, while (b) is relevant for certification. And I realized that these two schemes are not coupled in any way.

2. I stumbled upon this casual explanation of the certification election process by @garloff in some PR [comment](https://github.com/SovereignCloudStack/standards/pull/252#issuecomment-1477045357):
> By merging this [proposal], it becomes a merged draft standard which then goes into stabilization.
> As soon as it is stabilized, it becomes eligible to be chosen as a certification requirement for IaaS SCS-compatible certification. If we elect to do so, we would incorporate it into Tests/scs-compatible.yaml.

It appears to me that this process has not yet been documented.

# Action items
- [ ] In line with the SIG meeting: Write an article for the docs page summarizing the certification process for the wider audience.
- [x] Extend the draft [scs-0003](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0003-v1-sovereign-cloud-standards-yaml.md) to include the election process (similar to the process documentation in [scs-0001#process](https://github.com/SovereignCloudStack/standards/blob/scs-0100-v1-entropy-revised/Standards/scs-0001-v1-sovereign-cloud-standards.md#process))

Please comment @garloff and @alexander-diab.

**Comment by mbuechse** [comment]
I'm still confused by the fact that [scs-compatible.yaml](https://github.com/SovereignCloudStack/standards/blob/main/Tests/scs-compatible.yaml) includes [scs-0100-v2](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v2-flavor-naming.md) even though this version is still in draft state, which seems to violate Kurt's explanation I quoted in the initial description:

> As soon as it is stabilized, it becomes eligible to be chosen as a certification requirement for IaaS SCS-compatible

So something is still wrong -- maybe we have been too quick to add stuff to the "official" yaml instead of [the other one](https://github.com/SovereignCloudStack/standards/blob/main/Tests/scs-compatible-test.yaml) that we have for internal testing purposes?

**Comment by garloff** [comment]
You are right that this is inconsistent.
We should have stabilized scs-0100-v2 a long time ago and certainly before making it a certification requirement in scs-compatible.yaml.
One reason was probably that we wanted to start v2 compliance testing and display the results of the CI jobs on github/SCS/Standards.
I guess we should have an scs-compatible-future.yaml or so that we can use to test things that we intend to stabilize and make a certification requirement but have not yet gone through the process of creating full alignment yet.

For the specific v2 situation: As v1 is still allowed, we don't cause any trouble yet for our partners by referencing it. This will change in October, so we need to have everything cleaned up by then. The earlier the better of course.

As we are already discussing scs-0100-v3, maybe this is what we should push for broad agreement and once reached properly stabilize and make it a cert requirement. As v3 is very similar to v2 (making 13 previous v2 mandatory flavors recommended and just adding two mandatory SSD flavors (scs-0110-v1) that we agreed a long time ago and which many of our partners have already), we would more or less skip v2...

**Comment by garloff** [comment]
PS: Agree on your proposal to extend scs-0003 and blog about it.

**Comment by mbuechse** [comment]
On a less philosophic note, I don't seem to understand why the hierarchy in the yaml is "layer, then version" and not the other way around when the test script specifically tests the same version for every requested layer (except no version is given, which makes no sense for the certification badges).

**Comment by mbuechse** [comment]
Proposal to extend [scs-0003-v1-sovereign-cloud-standards-yaml](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0003-v1-sovereign-cloud-standards-yaml.md) as follows:
    * Maybe emphasize that the words "layer" and "level", though close syntactically and in vernacular semantics, refer to very distinct concepts.
    * Paint a picture of a scenario where some CSP has some certain combination of certifiable items and some other CSP has some other combination.
    * Give "certifiable item" a better name! (I guess I mean the combo of Level/Layer, sometimes with Version, sometimes without.) Maybe _certification package_?
    * Provide a hint as to what number of active versions we intend to deem reasonable for any fixed certification package.
    * Say that, from a technical perspective, certification levels are orthogonal -- dependency is not of a technical nature, but rather a progression like in a computer game. Maybe call it *prerequisite* instead?
    * Say that the certification package \<level N + 1\> \<layer X\> requires \<level N\> \<layer X\> -- not all layers of level N!

**Comment by fkr** [comment]
> Give "certifiable item" a better name! (I guess I mean the combo of Level/Layer, sometimes with Version, sometimes without.) Maybe certification package?

_certification set_ ?

**Comment by mbuechse** [comment]
For some reason, the link didn't get established automatically, so here is the pull request: https://github.com/SovereignCloudStack/standards/pull/329

**Comment by anjastrunk** [comment]
Issue closed as documentation will be part of SovereignCloudStack/docs/pull/76
