### ISSUE TITLE
Integrate OpenStack Metering Deployment in testbed

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#346]
As a CSP, I want to use the metering tool in osism.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] https://github.com/osism/container-images/pull/310
- [x] https://github.com/osism/ansible-collection-services/pull/1091
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by cah-link** [comment]
https://github.com/osism/ansible-collection-services/pull/1091

**Comment by cah-link** [comment]
The PR for the image build pipeline
https://github.com/osism/container-images/pull/310

**Comment by fkr** [comment]
Currently being reviewed in OSISM

**Comment by cah-link** [comment]
PR for adding json http endpoint as ceilometer publisher https://github.com/osism/testbed/pull/1704

**Comment by cah-link** [comment]
https://github.com/osism/ansible-playbooks/pull/307 added the metering role

**Comment by garloff** [comment]
Currently testing, little bugs still to be resolved.

**Comment by cah-link** [comment]
PR https://github.com/osism/testbed/pull/1719/files

depends on https://github.com/osism/cfg-generics/pull/358
and https://github.com/osism/container-image-kolla-ansible/pull/505

**Comment by fkr** [comment]
Update during today's IaaS call by @berendt: the integration into the testbed has been completed.
