### ISSUE TITLE
User Documentation for SCS Zuul

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#351]
As a SCS Developer, I want to easily onboard CI tasks to the SCS Zuul.
For this I need a guide or documentation on how to achieve that and what the processes are to achieve this.

## Definition of Ready:

- [X] User Story is small enough to be finished within one sprint
- [X] User Story is clear and understood by the whole team
- [X] Acceptance criteria are defined
- [X] Acceptance criteria are clear and understood by the whole team

## Acceptance Criteria
- [ ] SCS Zuul user documentation exists that is easy to understand and describes all steps and processes needed to onboard Repos, Jobs, Tasks, etc. to our Zuul CI tooling 

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] Documentation has been updated

**Comment by maxwolfs** [comment]
SCS Zuul user documentation should go here: https://github.com/SovereignCloudStack/docs/tree/main/operations/operations

**Comment by mbuechse** [comment]
Is this still being worked on? The PR seems to have been lying dormant for quite a while...

**Comment by fkr** [comment]
> Is this still being worked on? The PR seems to have been lying dormant for quite a while...

@master-caster is currently on vacation. He'll back next week.

**Comment by master-caster** [comment]
The quickstart guide was updated. Waiting for response.

**Comment by berendt** [comment]
@master-caster Can you add a link here?

**Comment by master-caster** [comment]
Quickstart guide was introduced to docs repo.
