### ISSUE TITLE
Extend compliance checker in Zuul to be able to consume multiple cloud environments

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#354]
The compliance check in zuul needs to be extended, in order for it to be easily extendable to further scs environments by simply adding more credentials.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by okautz** [comment]
As far as I see it this was done with: https://github.com/SovereignCloudStack/standards/issues/316

so I close this
