### ISSUE TITLE
Keystone: Multivalue group mapping not working

### ISSUE THREAD

**Issue by JuanPTM** [SovereignCloudStack/issues#358]
The group mapping for federation users is not working.

In the initial test, the multivalue mapping didn't work. To reduce to the simplest case the mapping of a hardcoded single group into federated users was tested and also failed.

Follow debuging and researching why and how to adjust the mapping rules.

**Comment by JuanPTM** [comment]
https://specs.openstack.org/openstack/keystone-specs/specs/keystone/ussuri/expiring-group-memberships.html

If I understood it correctly the group membership is not persisted in the database. Only the token carry it over.

**Comment by JuanPTM** [comment]
To conclude our findings from the previous post, we had an experiment of issuing a token from the openstack CLI.

```
RESP BODY: {"token": {"methods": ["openid"], "user": {"domain": {"id": "7ca8bbb8cb29428eb829346acb2ed8c1", "name":"keycloak"}, "id": "e1ef330bf98cc858d1f39b74dd427e60aeb23774512dc71ad9b26b2f89a3e81d", "name": "alice","OS-FEDERATION": {"groups": [{"id": "2da45684552e42f78d4e361b2fe8588f"}], "identity_provider": {"id":"keycloak"}, "protocol": {"id": "openid"}}}, "audit_ids": ["o209IRkUS_WebZ3dYc8bUQ"], "expires_at":"2023-07-15T09:49:53.000000Z", "issued_at": "2023-07-14T09:49:53.000000Z"}}

```

As the article says, the group membership is tracked on the token not on the openstack user model. I will verify if this works for multivalued groups membership and close the issue if it does.

**Comment by JuanPTM** [comment]
Even tho we have clarify how the group mapping works, we still have the problem that the multivalue group mapping is not working.

The reason for not working after debugging is the following one.

The mapping engine expects the structure of the groups in the claim to be the following one : 

```
group: [{name:group1},{name:group2}]
```

Meanwhile using `mod_auth_openidc` and the mapping rules the better we can get is:

`mod_auth_oidc` sends  `[g1;g2;g3]` then the mapping engine transform it to `"['g1','g2','g3']"` and after apply the rules it becomes:

```
group: [{name:[group1;group2;group3]}]
```

To our (@reqa and myself) opinion the mapping engine has an incomplete implementation. For the moment I've patched our testbed to properly work.

**Comment by reqa** [comment]
As Github somehow denies to attach diff files (even as .txt) I've pushed Juanpes patch proposal to https://github.com/reqa/keystone/tree/reqa/SovereignCloudStack%23361

**Comment by reqa** [comment]
As Github somehow denies to attach diff files (even as .txt) I've pushed Juanpes patch proposal to https://github.com/reqa/keystone/tree/reqa/SovereignCloudStack%23361

**Comment by garloff** [comment]
Background discussion with Kristi Nicola without feedback thus far.
Next step: Start review on gerrit. (AI @juantpm)

**Comment by JuanPTM** [comment]
I have created a patch upstream, and a bug on launchpad.

https://review.opendev.org/c/openstack/keystone/+/891315
https://bugs.launchpad.net/keystone/+bug/2031642

**Comment by JuanPTM** [comment]
The bug and the patch upstream has been closed. I've found a way to use the current mapping rules to make the multivalue groups claim work.

This is the current configuration for the mapping rules.

```
[
    {
        "local": [
            {
                "user": {
                    "name": "{0}",
                    "email": "{1}",
                    "domain": {
                        "name": "keycloak"
                    }
                },
                "domain": {
                        "name": "keycloak"
                    },
                "groups": "{3}","domain":{"name":"keycloak"},
                "projects": [
                    {
                        "name": "{2}",
                        "roles": [{"name":"member"}]
                    }
                ]
            }
        ],
        "remote": [
            {
                "type": "OIDC-preferred_username"
            },
            {
                "type": "OIDC-email"
            },
            {
                "type": "OIDC-openstack-default-project"
            },
            {
                "type": "OIDC-groups"
            }
        ]
    }
]
```

**Comment by garloff** [comment]
Upstream documentation should be improved, @reqa.
SCS implementation to be fixed (testbed, production).
Probably should be mentioned in SCS documentation / design doc.

**Comment by garloff** [comment]
@reqa to add link to upstream issue/review and close this.

**Comment by reqa** [comment]
I've created https://review.opendev.org/c/openstack/keystone/+/895978
