### ISSUE TITLE
Research: Ephemeral users in Keystone

### ISSUE THREAD

**Issue by JuanPTM** [SovereignCloudStack/issues#359]
ephemeral users (i.e. those from federtion) are not showing any group memberships in openstack, but you can add the manually. How is this intended to work in openstack? Dynamically during API endpoint access?

Research how this works

**Comment by reqa** [comment]
I guess https://www.youtube.com/watch?v=byobgGTiuK0&t=724s covered a bit of this and @JuanPTM extracted some points from it that confirm what he found in experiments with the testbed.

**Comment by garloff** [comment]
Research is complete, followup work in #405 .
