### ISSUE TITLE
Document roles and parameters

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#36]
As the maintainer of the documentation, I need to document the defined set of roles and parameters.

## Definition of Ready:

- [x] Set of defined roles and parameters is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All defined roles and parameters are documented
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by fkr** [comment]
https://github.com/osism/ansible-collection-commons/pull/351

**Comment by garloff** [comment]
20 PRs from Ramona in progress. (Jens & CB & MF reviewing & fine-tuning).
Cleaning up along the way, avoiding redundancy.

**Comment by fkr** [comment]
List of open PRs by @ra-rau 

- [ ] https://github.com/osism/ansible-collection-services/pulls
- [ ] https://github.com/osism/ansible-collection-validations/pulls

**Comment by tibeer** [comment]
Closing this issue as the above thinks have been done already.
