### ISSUE TITLE
Extend status-page web application to allow sign-in with github IdP

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#368]
The status-page web application needs to allow a sign-in with an IdP so that the policy layer can evaluate wether a user is allowed to access certain resources.

## Definition of Ready:

- [x] #365
- [x] #367 
- [x] #627 
- [x] #628 

## Definition of Done:

- [ ] As a user of the status-page web application I can click on a button and sign in with github

**Comment by berendt** [comment]
Why GitHub? At least when I use this as a CSP I want to use my internal IdP (Keycloak at the moment). If a customer needs a login via IdP, this will probably also be the internal IdP and not one of the public IdPs like GitHub.

**Comment by fkr** [comment]
Because this is about having a quick result for evaluating the flow between the frontend application, the policy layer and the backend.

**Comment by joshuai96** [comment]
@berendt as it currently stands, [dex](https://dexidp.io/) will be the central component regarding AuthN. dex uses [conectors](https://dexidp.io/docs/connectors/), which configure upstream IdPs. So switching between GitHub and LDAP for example, is just a matter of configuration.

**Comment by joshuai96** [comment]
The title of the issue caused some confusion. The web application should not authenticate with GitHub directly, but with the deployed Dex, which in turn is configured to log in with GitHub.
