### ISSUE TITLE
MVP3 for status page: CUD for status-page and metrics

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#369]
As an authenticated user of the status-page web applicaton I should be able to create and update incidents.

## Definition of Ready:

- [x] #612 
- [x] #627 
- [x] #628
- [x] #368 
- [x] #629
- [x] #630
- [x] #653 
- [x] #682 
- [x] #720 

## Optional
- [x] #631

## Definition of Done:

- [x] With an authenticated user, I can create a new incident through the status-page web application
- [x] With an authenticated user, I can update an existing incident through the status-page web application

**Comment by joshuai96** [comment]
Monitoring has been marked as done, as https://monitoring.scs.community/ now includes the status page metrics.

**Comment by snkaupe** [comment]
Finally completed with our release 1.0. 
https://github.com/SovereignCloudStack/status-page-api/releases/tag/v1.0.0
https://github.com/SovereignCloudStack/status-page-web/releases/tag/v1.0.0
https://github.com/SovereignCloudStack/status-page-deployment/releases/tag/v1.0.0
