### ISSUE TITLE
Create label to trigger e2e test

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#379]
As a trusted reviewer, I want to mark a pull request (PR) with the label `e2e-quick` so that the CI pipeline can perform a quick test using CI pipelines. For a full test I want to use the label `e2e-conformance`

**Comment by chess-knight** [comment]
I created following labels in [k8s-cluster-api-provider](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/labels) project:
- e2e-test
- e2e-quick-test
- successful-e2e-test
- successful-e2e-quick-test
- failed-e2e-test
- failed-e2e-quick-test
- cancelled-e2e-test
- cancelled-e2e-quick-test

![Screenshot from 2023-09-08 15-46-44](https://github.com/SovereignCloudStack/issues/assets/72069445/e59ae940-934b-4de8-a776-8055d7ac6767)
