### ISSUE TITLE
Open our community to new interests (self-service on-boarding)

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#38]
Idea from @tibeer - that originated from his README.md for the contributor guide

* reduce usage of mailing lists drastically
* reduce amount of mailing lists
* use single source of annoucement
* don't spam the mailing lists with complete annoucements, but rather the link to the annoucement!
* provide ONE single URL for all services with proper subdomains:
  - nextcloud.sovereignit.de
  - lists.sovereignit.de
  - jitsi.sovereignit.de
  - sovereignit.de (website)
I've never understood why there is scs.community and scs.sovereignit.de

* I would love to have a single tool for chat and video calls (slack, zulip, rocket chat, mattermost, element matrix, microsoft teams, i don't care)
* overall documentation is too much distributed. I would expect this "https://scs.community/docs/contributor/" to be available as a menu * point directly in "https://scs.community/". AND: I would expect it to be in the same design style. Would make things feel much more smooth.
* discussion point: add an "onboarding" channel in the desired instant messaging tool

**Comment by itrich** [comment]
@fkr @tibeer I scheduled a meeting on Wednesday, 2022-05-04. Are you in?

**Comment by tibeer** [comment]
@itrich depends, which time?

**Comment by fkr** [comment]
Between 11 and 14 is ok.

**Comment by itrich** [comment]
See: https://ms.scs.sovereignit.de/nextcloud/apps/calendar/p/TeqXXHaCPCwS2Dz8
The meeting is scheduled for 11 – 12 CET.

**Comment by tibeer** [comment]
👍  works for me

**Comment by itrich** [comment]
> * provide ONE single URL for all services with proper subdomains:
>   
>   * nextcloud.sovereignit.de
>   * lists.sovereignit.de
>   * jitsi.sovereignit.de
>   * sovereignit.de (website)
>     I've never understood why there is scs.community and scs.sovereignit.de

We should consider this (old) discussion regarding the single URL topic: https://github.com/SovereignCloudStack/issues/issues/5

**Comment by tibeer** [comment]
> > * provide ONE single URL for all services with proper subdomains:
> >   
> >   * nextcloud.sovereignit.de
> >   * lists.sovereignit.de
> >   * jitsi.sovereignit.de
> >   * sovereignit.de (website)
> >     I've never understood why there is scs.community and scs.sovereignit.de
> 
> We should consider this (old) discussion regarding the single URL topic: #5

I just noticed that there is also sovereignit.cloud (https://ui.gx-scs.sovereignit.cloud/auth/login/?next=/)

**Comment by itrich** [comment]
# Results of the first meeting

## Mailing lists
- Write a short summary for the Contributor Docs on how to properly use the mailing lists.
- Appeal to start mails with a short TL;DR, especially when forwarding mails from other mailing lists (e.g. Gaia-X)
- Appeal to add tags to the mail subject (e.g. [Team 2], [SIG Monitoring], etc.)
- Move technical discussions to GitHub issues and discussions

## URL
- Write a short summary of all SCS services for the Contributor Docs. This should be an entry point for every new and old community member.

## Chat
- Matrix is to be prefered as single solution for communication and should be promoted by our members. OSISM will move their community space to Matrix.
- Write a blog post to promote Matrix as communication platform.
- Add a channel for onboarding and new members. Be reactive and welcoming to new guests!

## Nextcloud
Try to make Nextcloud obsolete and move any files that is shared with the community (e.g. minutes) to GitHub.

**Comment by itrich** [comment]
Further minutes of our SIG community calls will be placed here: https://github.com/SovereignCloudStack/minutes/tree/main/sig-community

**Comment by itrich** [comment]
Blocked by #144
