### ISSUE TITLE
Document IAM design and status

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#397]
As an SCS operator setting a new cloud, I want to know how to configure my IAM components such that federated users work the way as intended by SCS.
I want to understand what I need to tell users, what this means for security, what things to avoid, what things are not working (yet).

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by reqa** [comment]
I've also created a draft for a blog article: https://github.com/SovereignCloudStack/website/pull/728

**Comment by garloff** [comment]
Blog article is live: https://scs.community/2023/09/05/progress-openstack-cli-with-federation/

**Comment by garloff** [comment]
Good progress in https://github.com/SovereignCloudStack/docs/pull/72, more work needed.

**Comment by garloff** [comment]
Completed.
