### ISSUE TITLE
Provide a Kubernetes cluster for core infrastructure services

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/issues#4]

**Comment by garloff** [comment]
I have started the creation of a k8s cluster with magnum on CN. This is still the free tier, which should be OK for testing.
Once we start with the project we can move over to a paid tenant.
Notes:
* I wanted to avoid the proprietary CCE implementation on OTC
* The magnum templates have somewhat old k8s -1.15 and I have created a 1master(2/4) + 3nodes(4/8) setup.

Let me know if you have more specific requirements.

**Comment by berendt** [comment]
@joshmue @tibeer I don't know what our requirements are. 1.15 sounds pretty old?

**Comment by tibeer** [comment]
I think so, too. But 1.15 should work for an initial test. @joshmue what do you think?

**Comment by joshmue** [comment]
Flux2 as well as the harbor helm chart require a more recent K8s release, I'm afraid. According to docs, [flux2 requires K8s 1.16](https://toolkit.fluxcd.io/guides/installation/#prerequisites) and [harbor-helm requires K8s 1.18](https://github.com/goharbor/harbor-helm/blob/master/README.md#prerequisites) right now.

**Comment by garloff** [comment]
Hmmm ...

Beyond magnum, CityCloud allows for an alternative way to create k8s clusters using rancher/rke. It's not completely trivial though. It looks to me like this would result in k8s >= 1.16, though probably one can control this by using or creating the right templates and images.
Obviously, with magnum, we could also create templates that have newer k8s.
Doing this as one-off is more effort than I can personally spend on this at this moment. @toberrydberg: Is providing magnum templates with k8s-1.19 something you have on the agenda short-term?

Looking at the OpenTelekomCloud option: I see k8s-1.17 in their (proprietary!) Cloud Container Engine (CCE) -- I could also ask if they plan to add an 1.19 option shortly (they only do uneven numbers).

We have magnum available in pluscloud demonstrator (gx-scs) as well, but I can't see any templates being defined yet (openstack coe cluster template list is empty). Should we try to integrate one working template into OSISM's deployment so we can more easily bootstrap? Sounds a bit more attractive than k3s to me, but I'm open ...

**Comment by berendt** [comment]
Supporting Magnum in OSISM makes no sense. We don't want that as a solution in the future. So we should not suggest that we are working on it now.

The manual setup of Rancher on the Citycloud also makes no sense.

We do not want to use the pluscloud demonstrator for the core infrastructure because it is a demonstrator.

For me it makes the most sense to build a Kubernetes cluster with Kops on the Citycloud and to use it first for the core infrastructure.

**Comment by tobberydberg** [comment]
For magnum, I will look at the plans for a newer version of k8s available in the public templates.

I agree that Rancher option right now isn't very well suited to be tested in this way since it isn't super well integrated with our management platform at the moment, so it will become pretty hard.

After the meeting we had regarding Gardner last friday I will drive that internally and hope to get us onboard that path.

**Comment by garloff** [comment]
The cluster has been provided (k8s-1.18.6 on citycloud).
