### ISSUE TITLE
Decide whether a backup of zuul is needed or not

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#400]
It is currently not clear wether a backup of the SCS Zuul is needed and IF it is needed what it should cover.
This needs to be found out and documented.

## Definition of Done:

- [ ] We're able to decide wether we need a backup or not

**Comment by o-otte** [comment]
This is needed at least for the decryption key for the secrets

**Comment by bitkeks** [comment]
Regarding the discussion of moving/migrating or re-deploying SCS Zuul and the related topic of Zookeeper and data base, I see this issue as "Doing".

**Comment by okautz** [comment]
@PixelPhantomX started on this to design an automation on saving dumps fo Zookeeper (Decryption Keys, State, etc.) and the MySQL (Former Builds)

edit: As Backups of Zookeeper and MySQL is decided and will be worked on. I will close this issue
