### ISSUE TITLE
Ensure OpenStack purge after each e2e run so multiple e2e runs do not interfere.

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/issues#407]
As an SCS operator, I want to be sure that OpenStack purge is issued after each e2e run so multiple e2e runs do not interfere.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by matofeder** [comment]
> In the OSISM testbed we decided to not use the OpenStack purge thing to be able to run multiple CI jobs inside the same project at the same time and wrote a script to cleanup everything created by a CI run. Maybe this is also helpful here: https://github.com/osism/testbed/blob/main/terraform/scripts/cleanup.py

Our plan is basically the same. 
Because KaaS cleanup scripts want some improvements [#484](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/484) we decided to use `ospurge` at the end of the CI pipeline and disable parallel runs of CI pipelines for now.  
Once [#484](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/484) is addressed we plan to replace `ospurge` with KaaS cleanup scripts and allow parallel CI runs against one OS project.

**Comment by garloff** [comment]
I believe that `make fullclean` is rather robust since the last improvements in #526 and #498.
Likewise, `cleanup.sh`/`delete_cluster.sh` have seen quite some improvements as well (#551, #550, #494).
So this can be reconsidered in the future, avoiding the restriction to have only one parallel job per OpenStack project.
But for now, let's first get this running reliably and then tackle parallelism.
