### ISSUE TITLE
Move the testbed federation configuration to the production repositories

### ISSUE THREAD

**Issue by JuanPTM** [SovereignCloudStack/issues#412]
We need to move the testbed federation configuration to the production repositories (`osism/defaults`, `osism/cfg-cookiecutter`, release notes) [see Testbed-vs-CiaB-vs-Production-Config](https://input.scs.community/2023-scs-team-iam#Testbed-vs-CiaB-vs-Production-Config-repo-input-cookiecutter-defaults)

## Definition of Done:

- [ ] federation from OpenStack to Keycloak can be optionally enabled
- [ ] the current state of `wsgi-keystone.conf` from the testbed is deployed as part of an SCS release
- [ ] all the configuration files are moved to the correct production repo
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by reqa** [comment]
Maybe @berendt can advise in the following point:

In the testbed repo we have https://github.com/osism/testbed/blob/main/scripts/deploy/200-infrastructure-services-basic.sh , but I don't know where this needs to go, also to cfg-cookiecutter?
The crucial call there is `osism apply --environment custom keycloak-oidc-client-config`

There is https://github.com/osism/ansible-collection-services/tree/main/roles/keycloak/tasks but the things that are done by `keycloak-oidc-client-config` are more keystone related (as client of Keycloak) and thus should be more closely located to the keystone deployment IMHO.

I could imagine that somewhere in https://github.com/osism/ansible-playbooks could be a suitable place?

**Comment by reqa** [comment]
In the testbed the genreal approach has been implemented via https://github.com/osism/testbed/pull/1415 , no clue how this is intended to be done in the proper osism release.

**Comment by berendt** [comment]
@reqa You have to add the playbook to https://github.com/osism/ansible-playbooks. I think it makes sense to add it as an infrastructure play (https://github.com/osism/ansible-playbooks/tree/main/playbooks/infrastructure).

I would not include it in the Keycloak role, as it is possible that Keystone is not yet usable when Keycloak is deployed.

**Comment by JuanPTM** [comment]
First merge request,in this case to osism/defaults : https://github.com/osism/defaults/pull/147

**Comment by reqa** [comment]
Looks like done, technically. I think we need to add some documentation how to adjust parameters for deployment, like setting `enable_keystone_federation` and `keystone_enable_federation_openid` to `yes` e.g. in `environments/kolla/configuration.yml`
