### ISSUE TITLE
SCS Zuul is deployed as a cluster

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#429]
As a SCS developer, I want my CI tool highly available so that run CI jobs anytime and be not blocked.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Zuul is deployed on multiple nodes
- [ ] Decide to cluster over multiple clouds
- [ ] Decide of Zuul should be deployed on a Kubernetes Cluster
- [ ] Adapt Deployment Scripts
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by okautz** [comment]
Implemented with https://zuul.sovereignit.cloud
