### ISSUE TITLE
SCS Zuul Decryption keys are saved regularly

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#431]
If an Zuul Instance needs to be recreated, we need to be able to re-encrypt used secrets. Those secrets are encrypted by Zuul and the decryption key is stored in the database. There are ways to export this key to be able to decrypt the secrets manually and re-encrypt them with the new key if necessary 

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Keys used by Zuul are exported and saved
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by okautz** [comment]
@PixelPhantomX started to work on this as of this week.

**Comment by PixelPhantomX** [comment]
I've made changes to ensure certs, zookeeper data and the mysql database are all stored on the VM.
https://github.com/SovereignCloudStack/zuul/pull/16

**Comment by PixelPhantomX** [comment]
Added a cronjob that will backup the Zuul master keys once a week, on Monday at 2am. This is backed up to the local VM in the existing Zuul certs directory.

**Comment by okautz** [comment]
Not an issue anymore with new instance at https://zuul.sovereignit.cloud
