### ISSUE TITLE
SCS Zuul uses the SCS Community IdP for authenticated access

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#432]
The SCS Zuul currently has no authenticated access configured. This means that some feature are not available like to re-enqueue failed periodic jobs.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Zuul uses the SCS Community UCS IdP for authenticated Access
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by okautz** [comment]
We discussed in the OPs Call that for know we want to use GitHub as the IdP. We will switch to Keycloak in the future.

Created PR to add a "Zuul Admins" Group (https://github.com/SovereignCloudStack/github-manager/pull/269) to the github manager.

In this group an Application will be created to use OAUTH2 OIDC to use with Zuul.

This will enable Zuul to use the Admin UI from within the WebUI according to the [Zuul documentation](https://zuul-ci.org/docs/zuul/latest/authentication.html#interfacing-with-other-systems).

**Comment by okautz** [comment]
Implemented in https://zuul.sovereignit.cloud
