### ISSUE TITLE
long (permanently) running implementation of cluster-api-provider for testing purposes

### ISSUE THREAD

**Issue by mxmxchere** [SovereignCloudStack/issues#435]
As a SCS-Developer and CSP who uses SCS to provide customer services, I want the cluster-api provider to be tested not only in "one-shot" scenarios but also in a "long-term" scenario so that:

- Role-distinction is tested not only in the real-world scenario but also in the test environment
- 1:n testing happens (1 cluster-api provider, with n > 1 clusters)
- Questions of CSP operations arise and can be addressed by SCS-Developers (for example: how to deploy cluster-api, how to update cluster api, tenancy separation, attachment of an IDP provider)

As a bonus we get a managed-k8s service that we can use for our testing ([dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food))

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Cluster is initially created on gxscs
- [x] Dex runs and is publicly available
- [x] Dex is configured to use GitHub as connector
- [ ] Members of SCS-Orga can authenticate with GitHub using Dex
- [ ] Cluster is appropriate documented

**Comment by NotTheEvilOne** [comment]
Progress is currently blocked because of missing sub-domain / Let's Encrypt or similar trusted certificate.

**Comment by jschoone** [comment]
Done with [moin-cluster](https://github.com/SovereignCloudStack/moin-cluster-config/)
