### ISSUE TITLE
Backup & Restore concept needed for k8s cluster

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#437]
As operator I need a way to backup and restore all objects of a k8s cluster, so I can recover from disasters (user errors, failed upgrades, catastrophic infra outage, ...).
As operator I also need (a cluster-specific) backup & restore for the management cluster.

### Definition of Done

- [ ] A proper backup and restore solution is found
- [ ] The solution supports all objects within the k8s cluster.
- [ ] Various disaster scenarios, such as user errors, failed upgrades, and catastrophic infrastructure outages can be handled
- [ ] Documentation with clear instructions on how to use it exists
- [ ] The backup and restore solution has been tested and approved by a third person

**Comment by jschoone** [comment]
This is covered in the registry work and can be adopted for other Kubernetes workloads as well.
https://docs.scs.community/docs/container/components/container-registry/docs/backup_and_restore
