### ISSUE TITLE
Create custom SONIC image

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/issues#444]
As an SCS developer, I want SONIC image to make networking on SONIC switches work and to deploy workloads to the lab.

The scope and requirements will be defined more by @berendt and @scoopex.

Tasks:

- [x]  Build generic SONIC image based on `202305`
- [x] Build a patched version of base `202305` fixing bug in management-framework user
- [x] Build specific images for purchased HW switches (dependency on testing requirements)
- [x] #484

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by akafazov** [comment]
TODO: describe management-framework bug
