### ISSUE TITLE
Document requirements and deployment of SONIC images and their operations

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/issues#445]
As an SCS community lab operator, I want to know how to deploy and operate SONIC images.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by ignatov17** [comment]
Documentation about deployment of SONIC images can be found at:
https://github.com/SovereignCloudStack/system-landscape/blob/main/hardware/network/FAQ_Edgecore.md#onie-install-sonic

**Comment by fdobrovolny** [comment]
Commit https://github.com/SovereignCloudStack/system-landscape/commit/3215a2bdd51f72f5c5fdcdad92046ffd62634584
