### ISSUE TITLE
Upstream domain-scoping for the domain list API to OpenStack

### ISSUE THREAD

**Issue by markus-hentsch** [SovereignCloudStack/issues#446]
To prevent the identity of customers/tenants getting exposed to each other, as a SCS provider I want my users with the "domain-manager" role to only see the domain they are authenticated in being listed when they use Keystone's domain list API.
A patch that provides proper domain scoping for this endpoint should be upstreamed.

Background: 

Some OpenStackClient and OpenStack SDK functions use the `list_domains` API to discover domain names by id and vice-versa. In order for the domain-manager role to function properly, access to this API is necessary (they need to be able to resolve domains when creating domain-soped IDM resources such as users, projects etc.). However, in its current implementation, OpenStack Keystone will return a list of all existing domains via its API with no ability to limit the list to the authenticated domain only using RBAC policies.

**Comment by markus-hentsch** [comment]
## Deep-dive analysis of domain scoping for other `identity:list_*` APIs

To understand how other API endpoints such as `identity:list_groups` or `identity:list_projects` implement domain scoping, I had a closer look at the implementation, its behavior and purpose.

Let's take for example the domain filtering for `identity:list_projects` which happens in [`keystone/api/projects.py:_list_projects()`](https://github.com/openstack/keystone/blob/653d82b1b4e09b2ff37b56868e57d08c8e3af7dd/keystone/api/projects.py#L111C17-L111C17):

```python
    def _list_projects(self):
        # ...
        target = None
        if self.oslo_context.domain_id:
            target = {'domain_id': self.oslo_context.domain_id}
        ENFORCER.enforce_call(action='identity:list_projects',
                              filters=filters,
                              target_attr=target)
        hints = self.build_driver_hints(filters)
        # ...
        refs = PROVIDERS.resource_api.list_projects(hints=hints)
        if self.oslo_context.domain_id:
            domain_id = self.oslo_context.domain_id
            filtered_refs = [
                ref for ref in refs if ref['domain_id'] == domain_id
            ]
        else:
            filtered_refs = refs
        return self.wrap_collection(filtered_refs, hints=hints)
```
(code slightly abridged at the `# ...` parts for readability)

There are two crucial parts of the domain-scoping:

**Part A: Policy enforcement check sync**

```python
        target = None
        if self.oslo_context.domain_id:
            target = {'domain_id': self.oslo_context.domain_id}
        ENFORCER.enforce_call(action='identity:list_projects',
                              filters=filters,
                              target_attr=target)
```

**Part B: Response content filtering**

```python
        if self.oslo_context.domain_id:
            domain_id = self.oslo_context.domain_id
            filtered_refs = [
                ref for ref in refs if ref['domain_id'] == domain_id
            ]
```

Here is my interpretation of the code:

Part **A** is actually not contributing to the filtering at all.
The core of the filtering is part **B**.
The `self.oslo_context` object stores information about the authentication of the user making the request, i.e. the scope of the Keystone token. This includes information like in which project or domain the user is authenticated in and with what role.
So part **B** is checking whether the user is authenticated in a domain-scoped fashion and if so, the result list of projects will be filtered for projects that match this domain.
Thus, the returned project list only contains projects from the same domain as the user.
If an administrator authenticated in system-scope makes the same request, the `else` branch of part **B** will trigger since there is no domain scope in the `self.oslo_context` object and the returned list will contain all projects instead.

Now for part **A**. The purpose of this part is not obvious at first.
The `enforce_call()` will check the Keystone policy definition (`identity:list_projects` in this case) against the authenticated user and will make the RBAC check if the user is allowed to execute this action.
When writing RBAC rules for the `policy.yaml` of an OpenStack component, the author can usually access attributes of the target resource. For example the policy rule:

```yaml
"identity:get_project": "'special-project':%(target.project.name)s"
```

... would check if the API response being targeted contains a `project` object whose `name` attribute matches "special-project" and only allows the request if that is the case. For this purpose, the Keystone code often fills a `target_attr` object for the enforcer which contains details about the resource that Keystone *would* return so that the policy checks can validate beforehand if it violates any RBAC definitions.
Now, for API endpoints that return a list, there is no single object returned. Hence, there normally would not be any specific attributes to check against. However since part **B** hardcodes that only objects matching the authenticated domain id will be returned, part **A** has one simply purpose: to reflect the hardcoded behavior of part **B** in the RBAC checks - namely the returned objects' domain.
Simply speaking it adds the information that the method will return only objects of this specific domain back to the RBAC layer, which would normally not be available there.
As a result, part **A** enables checks in the `policy.yaml` definitions that reference the domain id, for example:

```yaml
"identity:list_projects": "'34e03ce4b8454d6487e1bc3e561a4ba6':%(target.domain_id)s"
```

With this rule, listing projects would only work from within the domain with that id and nowhere else (it doesn't make sense and is just for demonstration purposes).

**Summary**

To summarize, part **B** implements a hardcoded behavior that automatically limits the resources returned in the `list_projects` to the domain the user making the request is authenticated in, if the user is authenticated in a domain-scoped fashion.

In case the request is domain-scoped, part **A** adds the information about the domain id membership of all returned objects (as implemented by part **B**) back to the RBAC policy checking layer, so that the additional information resulting from **B** can be used in policy definitions and checks.

**Comment by markus-hentsch** [comment]
## Keystone patch for domain lists that could be upstreamed

The same behavior as researched above for the `identity:list_projects` related endpoint can be replicated for `identity:list_domains`:

```diff
--- a/keystone/api/domains.py
+++ b/keystone/api/domains.py
@@ -99,11 +99,22 @@ class DomainResource(ks_flask.ResourceBase):
 
     def _list_domains(self):
         filters = ['name', 'enabled']
+        target = None
+        if self.oslo_context.domain_id:
+            target = {'id': self.oslo_context.domain_id}
         ENFORCER.enforce_call(action='identity:list_domains',
-                              filters=filters)
+                              filters=filters,
+                              target_attr=target)
         hints = self.build_driver_hints(filters)
         refs = PROVIDERS.resource_api.list_domains(hints=hints)
-        return self.wrap_collection(refs, hints=hints)
+        if self.oslo_context.domain_id:
+            domain_id = self.oslo_context.domain_id
+            filtered_refs = [
+                ref for ref in refs if ref['id'] == domain_id
+            ]
+        else:
+            filtered_refs = refs
+        return self.wrap_collection(filtered_refs, hints=hints)
 
     def post(self):
         """Create domain.
```

With this patch, only the domain the user is authenticated in is returned in the list, if the authentication is domain-scoped. If it is a system-scoped authentication by an administrator, the full list of domains is returned.

**Comment by berendt** [comment]
@markus-hentsch I will add this as a patch to latest OSISM Keystone images. I think it makes sense to have this already there.

**Comment by markus-hentsch** [comment]
In the Keystone PTG meeting on 2023-10-25, I was asked to create a Launchpad entry for Keystone upstream about this prior to submitting the patch, which I've now done here: https://bugs.launchpad.net/keystone/+bug/2041611

**Comment by markus-hentsch** [comment]
I just discovered that the patch proposed in https://github.com/SovereignCloudStack/issues/issues/446#issuecomment-1775337500 does not cover the following situation:

- user has a role assigned to them which is permitted in the `identity:list_domains` policy rule **wihtin a project**
  - e.g. `openstack role add --user some-user --project some-project domain-manager`
- user authenticates with a project-scoped token (see `openrc` example below) instead of the domain scope, like the Domain Manager usually would

`openrc` example for project-scoped authentication:
```
export OS_REGION_NAME=...
export OS_AUTH_URL=...
export OS_IDENTITY_API_VERSION=3
export OS_AUTH_TYPE=password
export OS_PASSWORD=...
export OS_USERNAME=some-user
export OS_USER_DOMAIN_NAME=some-domain
export OS_PROJECT_NAME=some-project
export OS_PROJECT_DOMAIN_NAME=some-domain
unset OS_DOMAIN_NAME
unset OS_PROJECT_DOMAIN_ID
unset OS_USER_DOMAIN_ID
```

... this results in all domains being exposed again to simple users. Since the Domain Manager standard allows CSPs to also allow self-service management of the domain-manager role, tenants might erronously give users the domain-manager role in a project and trigger this vulnerability.

Reason is because the `oslo_context` object has no `domain_id` set and the filter check fails.
I need to revise the patch to account for project scope as well!

**Comment by fkr** [comment]
As a comment, @markus-hentsch 👍🏻  on your work here - very much enjoy how this moves foward. Looking forward to a revised patch set.

**Comment by markus-hentsch** [comment]
## Analysis of identity:list_* action domain scoping code behavior

### Existing `list_*` endpoints

The following concerns endpoints list_projects and list_groups.

The policy rule component "`token.domain.id:%(target.domain_id)s`" results in a crucial difference in behavior.
Without this confinement, a project-scoped token can see objects from other domains.
Adding this confinement prevents this.

#### Constellation A: `list_*` without policy confinement

Policy:

```yaml
identity:list_groups: role:member or rule:admin_required
```

- admin: returns all groups
- domain-scoped token (domain is domain2): returns only groups of domain2
- project-scoped token (project within domain2): returns all groups

#### Constellation B: `list_*` with policy confinement

Policy:

```yaml
identity:list_projects: (role:member and token.domain.id:%(target.domain_id)s) or rule:admin_required
```

- admin: returns all groups
- domain-scoped token (domain is domain2): returns only groups of domain2
- project-scoped token (project within domain2): **returns only groups of domain2**

---

### Patched `list_domains` endpoint

When patching the list_domains endpoint with the following patch to mimic the domain-scoping behavior of the other list_* endpoints, its constellation A matches the others but constellation B does not work.

```diff
--- a/keystone/api/domains.py
+++ b/keystone/api/domains.py
@@ -99,11 +99,22 @@ class DomainResource(ks_flask.ResourceBase):
 
     def _list_domains(self):
         filters = ['name', 'enabled']
+        target = None
+        if self.oslo_context.domain_id:
+            target = {'domain_id': self.oslo_context.domain_id}
         ENFORCER.enforce_call(action='identity:list_domains',
-                              filters=filters)
+                              filters=filters,
+                              target_attr=target)
         hints = self.build_driver_hints(filters)
         refs = PROVIDERS.resource_api.list_domains(hints=hints)
-        return self.wrap_collection(refs, hints=hints)
+        if self.oslo_context.domain_id:
+            domain_id = self.oslo_context.domain_id
+            filtered_refs = [
+                ref for ref in refs if ref['id'] == domain_id
+            ]
+        else:
+            filtered_refs = refs
+        return self.wrap_collection(filtered_refs, hints=hints)
 
     def post(self):
         """Create domain.
```

Note: it does not matter whether "`target = {'domain_id'`" or "`target = {'id'`" is used in the implementation, as long as the policy rule's "`%(target.ATTRIBUTE)s)`" is adjusted accordingly.
We use "`domain_id`" here to keep the implementation close to the existing endpoints.

#### Constellation A: `list_domains` without policy confinement

Policy:

```yaml
identity:list_domains: role:member or rule:admin_required
```

- admin: returns all domains
- domain-scoped token (domain is domain2): returns only domain2
- project-scoped token (project within domain2): returns all domains

Note: using the patch set this now matches constellation A for the existing list_groups and list_projects endpoints.

#### Constellation B: `list_domains` with policy confinement

Policy:

```yaml
identity:list_domains: (role:member and token.domain.id:%(target.domain_id)s) or rule:admin_required
```

- admin: returns all domains
- domain-scoped token (domain is domain2): returns only domain2
- project-scoped token (project within domain2): **returns an error**

Error when using the project-scoped token:

```
You are not authorized to perform the requested action: identity:list_domains. (HTTP 403)
```

---

The difference in behavior for constellation B cannot be explained by the filter code alone.

The patch for `list_domains` is actually incomplete as it does not unlock the endpoint for project-scoped tokens at all.

This can be seen in the Keystone log:

```
UserWarning: Policy "identity:list_domains": "role:reader and system_scope:all" failed scope check.
The token used to make the request was project scoped but the policy requires ['system'] scope.
```

This can be fixed with an extension to the patch:


```diff
--- a/keystone/common/policies/domain.py
+++ b/keystone/common/policies/domain.py
@@ -70,7 +70,7 @@ domain_policies = [
     policy.DocumentedRuleDefault(
         name=base.IDENTITY % 'list_domains',
         check_str=base.SYSTEM_READER,
-        scope_types=['system'],
+        scope_types=['system', 'domain', 'project'],
         description='List domains.',
         operations=[{'path': '/v3/domains',
                      'method': 'GET'}],
```

This makes the log message disappear.
However, project-scoped tokens will still fail at `list_domains`:

```
You are not authorized to perform the requested action: identity:list_domains. (HTTP 403)
```

---

## Analyzing the `target_attr` bevavior of the policy enforcer

Using a small patch we can make Keystone print the policy enforcement target just before the policy check happens

```diff
--- a/keystone/common/rbac_enforcer/enforcer.py
+++ b/keystone/common/rbac_enforcer/enforcer.py
@@ -122,6 +122,7 @@ class RBACEnforcer(object):
                          do_raise=do_raise)
 
         try:
+            LOG.debug(target)
             result = self._enforcer.enforce(
                 rule=action, target=target, creds=credentials, **extra)
             self._check_deprecated_rule(action)
```

D1) `target` object during domain-scoped project list:

```
{'target.domain_id': '1a1a793377464131a2744e27fec9bcdf'}
```

D2) `target` object during domain-scoped domain list:

```
{'target.domain_id': '1a1a793377464131a2744e27fec9bcdf'}
```

P1) `target` object during project-scoped project list:

```
{'user_id': '383db1d2867544639f619acf1359d5f2', 'target.user.id': '383db1d2867544639f619acf1359d5f2', 'target.user.name': 'domain2-project-user', 'target.user.domain_id': '1a1a793377464131a2744e27fec9bcdf', 'target.user.enabled': True, 'target.user.password_expires_at': None}
```

P2) `target` object during project-scoped domain list:

```
{}
```

This shows that the

```python
if self.oslo_context.domain_id:
```

part of the API code *only* triggers during domain-scoped token authentication at all.
It overwrites the `target` for policy checks completely.
In case of project-scoped authentication, the `target` object is assembled by Keystone itself.

There are two mysteries still to be solved according to these observations:

1. It is completely non-obvious how P1 magically satisifies "`token.domain.id:%(target.domain_id)s`" and hides foreign projects as long as this condition is present, since there is no "`target.domain_id`" in there.
Remember that removing "`token.domain.id:%(target.domain_id)s`" will make P1 return projects of all domains.

2. Now, P2 (our scoping-patched `list_domains` implementation) does not fill `target` at all since the auto-generation seems to fail in Keystone.

**Comment by markus-hentsch** [comment]
## Solving the puzzle

> It is completely non-obvious how P1 magically satisifies "`token.domain.id:%(target.domain_id)s`" and hides foreign projects as long as this condition is present, since there is no "`target.domain_id`" in there.
> Remember that removing "`token.domain.id:%(target.domain_id)s`" will make P1 return projects of all domains.

The observation here missed one crucial detail the whole time which only surfaces in the Keystone logs or the debug output of the client: the OpenStackClient is actually failing "`openstack project list`" in case the policy confinement is active and a project-scoped token is presented. It then makes a second call to `list_user_projects` in the background as a retry mechanism and returns its results - completely transparent to the user.

This means that given the policy ...

```yaml
identity:list_projects: (role:member and token.domain.id:%(target.domain_id)s) or rule:admin_required
```

... the initial request of the client to `list_projects` fails with a project-scoped token as there is no `domain_id` in the token.
The OpenStackClient then makes the request to `list_user_projects` and gets the list of the projects the user is in returned.
In my testing cases, this list coincidentally matched with all projects within that domain.

This led me to the false conclusion that some magic filtering is happening at the `list_projects` endpoint with a project-scoped token. However, it was simply the OpenStackClients doing.

This makes the behavior of the scoping-patched `list_domains` endpoint correct and in sync with the existing endpoints.

### Bottom line

The `list_domains`, `list_groups` and `list_projects` endpoints will behave in a similar fashion if the patch discussed above is applied.

There is a weakness to how Keystone does things in the policy mechanism.
Consider the following policies:

```yaml
identity:list_projects: (role:member and token.domain.id:%(target.domain_id)s) or rule:admin_required
identity:list_groups: (role:member and token.domain.id:%(target.group.domain_id)s) or rule:admin_required
identity:list_domains: (role:member and token.domain.id:%(target.domain_id)s) or rule:admin_required
```

*Without* the "`token.domain.id:%(...)`" parts, the following will happen:

- domain-scoped token: only resources of the same domain are returned
- project-scoped token: all resources across domains are returned

This is because the automatic domain filtering on those endpoints looks up the `domain_id` of the token but in case of a project-scoped token there is none. This is the same for the existing endpoints as well as the patched 'list_domains' one.
The automatic domain filtering in the Keystone code is insufficient in case custom policies are deployed. In such case the "`token.domain.id:%(...)`" check must be included.

---

The final patch could look something like this:

```diff
--- a/keystone/api/domains.py
+++ b/keystone/api/domains.py
@@ -99,11 +99,22 @@ class DomainResource(ks_flask.ResourceBase):
 
     def _list_domains(self):
         filters = ['name', 'enabled']
+        target = None
+        if self.oslo_context.domain_id:
+            target = {'domain': {'id': self.oslo_context.domain_id}}
         ENFORCER.enforce_call(action='identity:list_domains',
-                              filters=filters)
+                              filters=filters,
+                              target_attr=target)
         hints = self.build_driver_hints(filters)
         refs = PROVIDERS.resource_api.list_domains(hints=hints)
-        return self.wrap_collection(refs, hints=hints)
+        if self.oslo_context.domain_id:
+            domain_id = self.oslo_context.domain_id
+            filtered_refs = 
+                ref for ref in refs if ref['id'] == domain_id
+            ]
+        else:
+            filtered_refs = refs
+        return self.wrap_collection(filtered_refs, hints=hints)
 
     def post(self):
         """Create domain.
diff --git a/keystone/common/policies/domain.py b/keystone/common/policies/domain.py
index cd743ee90..393415a3a 100644
--- a/keystone/common/policies/domain.py
+++ b/keystone/common/policies/domain.py
@@ -70,7 +70,7 @@ domain_policies = [
     policy.DocumentedRuleDefault(
         name=base.IDENTITY % 'list_domains',
         check_str=base.SYSTEM_READER,
-        scope_types=['system'],
+        scope_types=['system', 'domain'],
         description='List domains.',
         operations=[{'path': '/v3/domains',
                      'method': 'GET'}],
```

This now needs a complementary policy rule like this:

```yaml
identity:list_domains: (role:domain-manager and token.domain.id:%(target.domain.id)s) or rule:admin_required
```

I have changed the structure of `target` in the code a bit in comparison to the previous patch snippet in the earlier comments.
Since it turned out that this variable does not trigger any auto-filtering magic after all, its structure can be arbitrary and only needs to be reflected in the policy rule.
For now I've settled for "target.domain.id" akin to way the `list_groups` endpoint structures it.

**Comment by markus-hentsch** [comment]
I finalized the patch, tested in on a DevStack, wrote unit tests and submitted the patchset to upstream: https://review.opendev.org/c/openstack/keystone/+/900028

**Comment by markus-hentsch** [comment]
The upstream Zuul test failed on my patchset because tempest-keystone-plugin now has incompatible tests to the changed behavior.

I brought this up in the weekly Keystone IRC meeting and asked how to approach this two-way dependency:

```
[16:35] <mhen> the unittests that I adjusted for this endpoint in the patchset expected a different behavior - I guess it's the same for the RBAC tests of the tempest plugin
[16:35] <mhen> so those need adjustments as well
[16:36] <mhen> I can also have a look myself but I'd need guidance on how I can make it so that it interlinks with the patchest in keystone to appease Zuul
[16:36] <mhen> *patchset
[16:37] <d34dh0r53> I would guide you to dmendiza[m], he knows the RBAC testing infra better than anyone
[16:38] <dmendiza[m]> 👀
[16:40] <d34dh0r53> :)
[16:40] <mhen> let's say I have two patchsets on review.opendev.org, one for keystone and one for keystone-tempest-plugin, how can I tell Zuul to test the former using the latter and not the current master branch of keystone-tempest-plugin?
[16:42] <dmendiza[m]> You can use "Depends-On:"
[16:43] <d34dh0r53> dmendiza[m], xek: does depends-on do that across projects?
[16:43] <d34dh0r53> ahh, yeah, what dmendiza[m] said :)
[16:43] <dmendiza[m]> e.g. make a patch for Keystone with the necessary changes, then in the tempest-plugin patch add "Depends-On: <url for keystone change>"
[16:43] <mhen> in the commit messag?
[16:43] <dmendiza[m]> yeah
[16:44] <mhen> alright, got it
[16:44] <dmendiza[m]> ... although now that I think about it, the keystone one needs to know about the tempest-plugin patch too because it also runs tempest.
[16:44] <mhen> yea that's the direction I was going for
[16:44] <dmendiza[m]> so maybe, what you need is to make the changes in keystone and also make the tempest job non-voting in the same patch (because we'll expect a failure)
[16:45] <d34dh0r53> yeah
[16:45] <dmendiza[m]> Then the tempest-plugin patch with "Depends-On: <url to keystone patch>" in the commit message
[16:45] <dmendiza[m]> then a third patch to re-enable the job in keystone that Depends-On the tempest-plugin patch
[16:48] <mhen> so I'd add "voting: false" to the "keystone-protection-functional" entry in .zuul.yaml ?
[16:48] <mhen> (to "make the tempest job non-voting")
[16:49] <dmendiza[m]> yep
```

([full IRC meeting log](https://meetings.opendev.org/meetings/keystone/2023/keystone.2023-11-08-15.00.log.html))

**Comment by markus-hentsch** [comment]
Necessary adjustments to keystone-tempest-plugin put up as a patchset here: https://review.opendev.org/c/openstack/keystone-tempest-plugin/+/900545

**Comment by josephineSei** [comment]
Due to the ongoing work of implementing secure RBAC upstream this patch was caught in a merge conflict. I resolved the conflicts in the policies and commited a new patch: https://review.opendev.org/c/openstack/keystone/+/900028

**Comment by josephineSei** [comment]
I am on it fixing the Errors in tox and will align the keystone patch with the tempest plugin patch, because the Policy names had to be changed.

**Comment by josephineSei** [comment]
My fixes were successful, I additionally asked for reviews in the IRC-channel.

**Comment by josephineSei** [comment]
Someone suggested in the comments of the patch, that it might break API for those who do not enforce scope. As fas as I have tested it again, it does not. But I asked dmendiza from upstream for a review, because he is also involved in the secure RBAC developlement and has a better overview  about the scopes.

**Comment by josephineSei** [comment]
I asked for reviews again and got a +2 from Dave, he want to also bring this topic up to the other cores.

**Comment by josephineSei** [comment]
our patch was merged upstream: https://review.opendev.org/c/openstack/keystone/+/900028
So I close this issue

**Comment by berendt** [comment]
@josephineSei Should a (downstream) backport be made for 2023.2 so that the patch is included in the next SCS release?

**Comment by josephineSei** [comment]
@berendt I would say yes, but we should discuss this in the IaaS meeting. There is a little bit of difficulty added, because the patch relies on a recent update of the policies which happened within this OpenStack cycle.

**Comment by berendt** [comment]
> @berendt I would say yes, but we should discuss this in the IaaS meeting. There is a little bit of difficulty added, because the patch relies on a recent update of the policies which happened within this OpenStack cycle.

Ok, we'll discuss this on Wednesday. But I think we'd rather not have a backport as we're already at the RCs and SCS probably won't be able to make any major adjustments at such short notice.

**Comment by fkr** [comment]
I added it to the agenda for wednesday.
One idea would be to bring it in a subsequent release to R6 such as a 7.1.0.

**Comment by josephineSei** [comment]
@markus-hentsch I noticed today, that the patch does not include the zuul.yaml, that excluded some tempest tests. However, the pipeline was green, otherwise it would not have been merged.

So I don't know, whether this: https://review.opendev.org/c/openstack/keystone-tempest-plugin/+/900545?tab=change-view-tab-header-zuul-results-summary is still required or not upstream.

Maybe we should ask upstream, what was done with the keystone pipeline and tests.

**Comment by markus-hentsch** [comment]
A patchset was still lingering concerning Keystone's tempest tests: https://review.opendev.org/c/openstack/keystone-tempest-plugin/+/900545/comments/c4d5de73_063eda62

I rebased this now, since in the meantime the upstream code about tests has changed a bit (as referenced in the review comment).

**Comment by markus-hentsch** [comment]
The fix for the domain-scoping has now been backported to the 2023.2 release:

https://bugs.launchpad.net/keystone/+bug/2041611/comments/5

**Comment by fkr** [comment]
thanks @markus-hentsch for your work and effort
