### ISSUE TITLE
VP04 User stories definition

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/issues#448]
As a SCS Devloper, I want to have scope for VP04 defined so that we are aligned on the work.

https://input.scs.community/vp04-user-stories

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by akafazov** [comment]
Defined user stories during working session.

**Comment by fdobrovolny** [comment]
Output of this task will be discussed with scs stakeholders to expand and select appropriate direction.
For lot 1 discussion did already happend.
For lot 2b task #462 was created.
