### ISSUE TITLE
Confidential computing - lightning talk

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#45]
As the SCS community, it would be lovely to have a lightning talk from Intel on how SGX is put to use - in a live demo.

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Recording of Talk has been published or it has actively been decided that it is not supposed to be published

**Comment by fkr** [comment]
Does not make sense to tackle before sometime in July.

**Comment by fkr** [comment]
Lightning talk was done last week. @itrich wants to see wether the recording can be published or not.

**Comment by fkr** [comment]
We're allowed to publish the video, will happen today.

**Comment by itrich** [comment]
Closed by https://www.youtube.com/watch?v=50GlMnIYhAc
