### ISSUE TITLE
Loading and testing SONIC images on lab hardware switches

### ISSUE THREAD

**Issue by akafazov** [SovereignCloudStack/issues#454]
As a an SCS developer, I want to load and test SONIC images so that find how to install and find possible issues connected with properly functioning of the installed SONIC image.

Tasks:
- [x] document installation and management of SONIC images
- [x] identify features to be turn off/on for different hardware
- [x] identify bugs/issues for HW/SW combinations

Working documents:
 - https://input.scs.community/JL5u1pNbT_WGWRCZT9zPqA?view
 - https://github.com/SovereignCloudStack/system-landscape/blob/main/hardware/network/Issues_SONIC.md

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by ignatov17** [comment]
Documentation for issues with SONIC images can be found at:
https://github.com/SovereignCloudStack/system-landscape/blob/main/hardware/network/Issues_SONIC.md

**Comment by ignatov17** [comment]
Created issue #459 for system-healt information in SONIC

**Comment by ignatov17** [comment]
Documentation about installation and management of SONIC images on Edgecore swithes can be found at:
https://github.com/SovereignCloudStack/system-landscape/blob/main/hardware/network/FAQ_Edgecore.md#onie-install-sonic

**Comment by ignatov17** [comment]
Issue for missing user admin in the mgmt-framework container #460

**Comment by ignatov17** [comment]
identified  bugs/issues for HW/SW are described in the document:
https://input.scs.community/JL5u1pNbT_WGWRCZT9zPqA?view
