### ISSUE TITLE
OpenstackAPI and Openstack internal Traffic TLS encryption

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/issues#457]
As an SCS Developer, I want to document a proposal and decision about Openstack API and OpenStack internal traffic encryption.

Draft is here https://input.scs.community/VP04-East-West-traffic-encryption

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
How exactly is East-West Traffic defined? IMO, it has nothing to do with internal services. East-West traffic is traffic between instances on an environment that does not leave the environment itself and does not touch the outer network perimeter.

**Comment by fdobrovolny** [comment]
:thinking: You are correct. I was working with the definition of East-West as internal services and North-South, as between non-OpenStack services and did not question it. Let me rename it.

**Comment by mpilka** [comment]
Notes:
1) OpenShift is mentioned multiple times, should it be OpenStack?
2) Let's use single OpenStack spelling: Openstack | openstack -> OpenStack
3) When Kolla is mentioned for the first time, it should be shortly introduced (one sentence is enough)
4) I encountered several typos, please use spell-checker

**Comment by fdobrovolny** [comment]
This has been supersceeded by #462
