### ISSUE TITLE
SONIC "show system-health" command error. 

### ISSUE THREAD

**Issue by ignatov17** [SovereignCloudStack/issues#459]
EPIC: #538 

As a an SCS developer, I want build a SONIC image so that to be installed and work properly on Broadcom switches.

Using image sonic-broadcom-bugfix1.bin on sw09 I have the following error:

Refers to https://github.com/SovereignCloudStack/issues/issues/444

```
admin@sw09:~$ sudo show system-health summary
System health configuration file not found, exit...
```

Device Model: [Edgecore 7726-32X-O-AC-B](https://github.com/SovereignCloudStack/system-landscape/blob/main/hardware/network/Edgecore_7726-32X-O-AC-B.md)
Device Serial No: 772632X2333075
Device Serial No: 772632X2333077

Resources:
- [Edgecore AS7326-56X switch specification](https://www.opencompute.org/documents/edgecore-networks-as7326-56x-25g-top-of-rack-switch#page=52&zoom=100,84,93).
- [Edgecore AS7726-32X switch specification](https://www.opencompute.org/documents/edgecore-networks-as7726-32x-32x100g-trident-3-based-switch)
- [SCS sonic-buildimage repository](https://github.com/SovereignCloudStack/sonic-buildimage)
- [Edgecore device drivers repo](https://github.com/edge-core/sonic-platform-modules-accton)
- SONIC WIKI [System Health HLD](https://github.com/sonic-net/SONiC/blob/master/doc/system_health_monitoring/system-health-HLD.md)

Current information on testing SONIC build-images can be found in document:
https://input.scs.community/HlTFVjFIS3umxZcSLOcZsQ?both

## Acceptance Criteria
- [x] user can execute `sudo show system-health summary` command without errors
- [x] bugfix should apply to all 100G switches (<100Gs are out of scope)
- [x] get GREEN SYS_LED reading from as7726 device
- [ ] get GREEN SYS_LED reading from as7326 device

**Comment by ignatov17** [comment]
Additional useful information:
https://github.com/sonic-net/sonic-buildimage/pull/6096

**Comment by ignatov17** [comment]
After building a new image (sonic-broadcom-fix2.bin), installing and testing it on sw09:

```
admin@sw09:~$ sudo show system-health summary
System health configuration file not found, using default health monitoring config...
chassis.set_status_led is not implemented
Traceback (most recent call last):
File "/usr/local/bin/show", line 8, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in call
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/show/system_health.py", line 114, in summary
_, chassis, stat = get_system_health_status()
File "/usr/local/lib/python3.9/dist-packages/show/system_health.py", line 33, in get_system_health_status
chassis.initizalize_system_led()
AttributeError: 'Chassis' object has no attribute 'initizalize_system_led' 
```

**Comment by akafazov** [comment]
New build: `/public_html/sonic-broadcom.bin-issue-#459` is uploaded to HTTP server.

**Comment by ignatov17** [comment]
With new build /public_html/sonic-broadcom.bin-issue-#459 I received the previous error:

```
admin@sw09:~$ sudo show system-health summary
System health configuration file not found, exit...
```

**Comment by akafazov** [comment]
Built 2 images, failed to resolve the issue.

Image build speedup improvements needed, in order to save time. Currently on hold while optimizing the build speed.

**Comment by fdobrovolny** [comment]
Speed optimization happens in #484

**Comment by ignatov17** [comment]
build image sonic-broadcom-fix-scs-459-dbg.bin on switch st01-sw25g-r01-u40 (SerialNo 732656X2317026) :

Device: Model: Edgecore 7326-56X-O-AC-B

```
admin@st01-sw25g-r01-u40:~$ sudo show system-health summary 
chassis.set_status_led is not implemented
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/show/system_health.py", line 113, in summary
    _, chassis, stat = get_system_health_status()
  File "/usr/local/lib/python3.9/dist-packages/show/system_health.py", line 32, in get_system_health_status
    chassis.initizalize_system_led()
AttributeError: 'Chassis' object has no attribute 'initizalize_system_led'
```

**Comment by akafazov** [comment]
> build image sonic-broadcom-fix-scs-459-dbg.bin on switch st01-sw25g-r01-u40 (SerialNo 732656X2317026) :
> 
> Device: Model: Edgecore 7326-56X-O-AC-B
> 
> ```
> admin@st01-sw25g-r01-u40:~$ sudo show system-health summary 
> chassis.set_status_led is not implemented
> Traceback (most recent call last):
>   File "/usr/local/bin/show", line 8, in <module>
>     sys.exit(cli())
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/show/system_health.py", line 113, in summary
>     _, chassis, stat = get_system_health_status()
>   File "/usr/local/lib/python3.9/dist-packages/show/system_health.py", line 32, in get_system_health_status
>     chassis.initizalize_system_led()
> AttributeError: 'Chassis' object has no attribute 'initizalize_system_led'
> ```

Analysis:
the wrong `chassis.py` is executed: /usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py
must be for the correct platform: /usr/share/sonic/device/x86_64-accton_as7326_56x-r0/sonic_platform/chassis.py

**Comment by akafazov** [comment]
Image `sonic-broadcom-fix_scs-459.0-dirty-20231208.165808.bin` fixes the issue on 100G models.

**Comment by ignatov17** [comment]
current information on testing SONIC build-images are in document:
https://input.scs.community/HlTFVjFIS3umxZcSLOcZsQ?both

**Comment by akafazov** [comment]
Error executing `parseDatabaseConfig` script for AS7326-56X device.

```syslog
2023-12-13T15:35:00.541725+00:00 sonic pre_pddf_init.sh[1011]: Error: Read failed
2023-12-13T15:35:00.541725+00:00 sonic pre_pddf_init.sh[1011]: Error: Read failed
2023-12-13T15:35:00.542040+00:00 sonic pre_pddf_init.sh[1008]: The board has system EEPROM at I2C address 0x57.
2023-12-13T15:35:00.542040+00:00 sonic pre_pddf_init.sh[1008]: The board has system EEPROM at I2C address 0x57.
2023-12-13T01:10:43.067653+00:00 sonic python: :- parseDatabaseConfig: Sonic database config file doesn't exist at /var/run/redis/sonic-db/database_config.json
2023-12-13T01:10:43.067653+00:00 sonic python: :- parseDatabaseConfig: Sonic database config file doesn't exist at /var/run/redis/sonic-db/database_config.json
```

The `pre_pddf_init.sh` errors shouldn't be an issue.

**Comment by akafazov** [comment]
The wrong `chassis.py` files is loaded

```bash
diff /usr/local/lib/python3.9/dist-packages/sonic_platform/chassis.py /usr/share/sonic/device/x86_64-accton_as7326_56x-r0/sonic_platform/chassis.py
```

**Comment by matofeder** [comment]
@scoopex it seems that  `get GREEN SYS_LED reading from as7326 device` is still open task here, could you please confirm, whether it is still that case?

**Comment by matofeder** [comment]
A custom SCS build of SONiC has resolved issues related to the `show system-health" command error.` The SCS build is based on the SONiC community version and contains unmerged PRs from the community repository; see https://github.com/SovereignCloudStack/sonic-buildimage/pull/4.

Test on multiple edge-core devices is described here https://github.com/SovereignCloudStack/issues/issues/706 

Considered as resolved
