### ISSUE TITLE
[Other] Items to be discussed in Team IaaS

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#46]
Items to be discussed in Sprint Planning / Refinement Team IaaS (Team 1)

- [x] https://github.com/osism/issues/issues/140
- [x] https://github.com/osism/issues/issues/189
- [x] https://github.com/osism/issues/issues/47 (needs refinement)
- [x] https://github.com/osism/issues/issues/191
- [x] https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1376

**Comment by berendt** [comment]
https://github.com/osism/issues/issues/169

**Comment by horazont** [comment]
In Yaook, we came across this topic: https://gitlab.com/yaook/operator/-/issues/272. Is this something we want to discuss in Team 1 some time maybe? I'd like to hear your experience regarding this and tips how we can improve our status quo.

**Comment by horazont** [comment]
Another topic from Yaook (yes, I'm cleaning up issues): https://gitlab.com/yaook/operator/-/issues/18. How does osism/kolla-ansible handle this? Is there any prepared guideline how to constrain the different nova/neutron/cinder keystone service accounts so that they can only do exactly what they are allowed to do? The background is to limit the damage credentials which have been exposed in some way can do.

**Comment by fkr** [comment]
- [ ] https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1376

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/215

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/223

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/225

**Comment by fkr** [comment]
[ ] https://github.com/osism/openstack-image-manager/pull/243

**Comment by fkr** [comment]
- [ ] benchmarks from PS reg. customer facing disk encryption

**Comment by fkr** [comment]
- [ ] OIF 2022 Watchlist  - https://input.osb-alliance.de/p/20220617-oif-summit-watchlist

**Comment by fkr** [comment]
- [ ] Monasca - https://wiki.openstack.org/wiki/Monasca

**Comment by fkr** [comment]
- [ ] https://github.com/SovereignCloudStack/Docs/pull/9

**Comment by fkr** [comment]
- [ ] this needs to be discussed

**Comment by fkr** [comment]
- [ ] zuul for scs

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/272

**Comment by fkr** [comment]
@berendt shouldn't this (https://github.com/osism/issues/issues/272) be discussed in Team OPS tomorrow?

**Comment by berendt** [comment]
> @berendt shouldn't this ([osism/issues#272](https://github.com/osism/issues/issues/272)) be discussed in Team OPS tomorrow?

Not sure about this. It affects the ES service of the infrastructure layer.

**Comment by fkr** [comment]
Discussion is ongoing and also moved to SIG monitoring. Thanks @berendt for raising it.

**Comment by berendt** [comment]
- [ ] https://github.com/osism/release/pull/586

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/360

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/361

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/369

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/368

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/370

**Comment by flyersa** [comment]
> * [ ]  [openstack: deprecate some openstack services osism/release#586](https://github.com/osism/release/pull/586)
> 
> ```
> * Heat is deprecated in favor of more generic Infrastructure as Code tools like Terraform
>    as of now and will be removed in the future (exact removal date is not yet known)
>  * Magnum (currently available as Technical Preview) will be removed in favor of Gardener and
>    Cluster API
>  * Mistral (currently available as Technical Preview) will be removed
>  * Swift (currently available as Technical Preview) will be removed in favor of Ceph RGW
>  * Trove (currently available as Technical Preview) will be removed in favor of Kubernetes
>    database operators
> ```

Why do you want to remove mistral? We have clients as example that use mistral to schedule automated snapshots and backups.

**Comment by fkr** [comment]
@flyersa afaik the reason is that there is a proposal upstream to deprecate Mistral: https://review.opendev.org/c/openstack/governance/+/866562

See this thread on OpenStack discuss: https://lists.openstack.org/pipermail/openstack-discuss/2022-December/031388.html

However, apparently OVH is stepping up to maintain mistral, so this could change things.

**Comment by berendt** [comment]
- [ ] have a look at https://github.com/ovh/distronaut (https://distronaut.ovh)
- [ ] decision for https://github.com/osism/cloud-in-a-box/issues/31

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/427

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/377

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/425

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/309

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/433

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/434

**Comment by berendt** [comment]
- [ ] https://github.com/osism/issues/issues/436 (also related to Team Kubernetes)

**Comment by fkr** [comment]
obsoleted by hedgedoc and the meeting preps there
