### ISSUE TITLE
User admin is not added in the mgmt-framework container of SONIC

### ISSUE THREAD

**Issue by ignatov17** [SovereignCloudStack/issues#460]
As a an SCS developer, I want to to build and test a SONIC image  so that image to be installed and work properly on Broadcom switches.

With build image sonic-broadcom.bin in cli console I received the following error:

```
admin@sonic: sonic-cli
sonic# configure terminal
sonic(config)# interface Ethernet 4
Traceback (most recent call last):
File "/usr/sbin/cli/sonic-cli-if.py", line 167, in
pipestr().write(sys.argv)
File "/usr/sbin/cli/scripts/rpipe_utils.py", line 14, in init
pwrec = pwd.getpwuid(os.getuid())
KeyError: 'getpwuid(): uid not found: 1000'
```
After investigation it was found that user admin is not registered in the mgmt-framework container of SONIC.

Refers to https://github.com/SovereignCloudStack/issues/issues/444

## Definition of Ready:

- [x]  find how to fix the error
- [x] build new image
- [x] install and test the image

**Comment by akafazov** [comment]
Test with new image was successful.
