### ISSUE TITLE
[Testing] Distributed K8s nodes to ensure Anti-Affinity (scs-0214-v1)

### ISSUE THREAD

**Issue by cah-hbaum** [SovereignCloudStack/issues#477]
After the [standard "Kubernetes Node Distribution and Availability" (scs-0214-v1)](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0214-v1-k8s-node-distribution.md) was created in https://github.com/SovereignCloudStack/issues/issues/434, the tests for this standard now need to be written.

Part of https://github.com/SovereignCloudStack/standards/issues/481.

## Definition of Done:

- [x] Write a test for distribution of K8s nodes (https://github.com/SovereignCloudStack/standards/pull/486)
- [ ] Integrate the test in Zuul (https://github.com/SovereignCloudStack/standards/pull/484)
- [x] Review for the PR passed

**Comment by mbuechse** [comment]
The test is not yet integrated in Zuul, but it will be with <https://github.com/SovereignCloudStack/standards/issues/485>.

**Comment by cah-hbaum** [comment]
I just reopen it until the Zuul part is done.

**Comment by mbuechse** [comment]
Please don't. The Zuul part is a totally separate issue. I don't understand why it was part of this issue in the first place.
