### ISSUE TITLE
There exist Dashboards for SCS services endpoinds health (BlackBox exporter)

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/issues#480]
As a CSP, I want see the health of  SCS services endpoinds (BlackBox exporter) so that I can easily see if there is an incident and can act fast to mitigate an issue.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
For the IaaS layer we started to collect Grafana dashboards in https://github.com/osism/kolla-operations/tree/main/grafana/dashboards. Most of them are probably out of date and in a bad state.

All of the dashboards in the osism/kolla-operations repository are imported in the Grafana service (the Grafana service itself is deployed with the Grafana role of kolla-ansible: https://github.com/openstack/kolla-ansible/tree/master/ansible/roles/grafana).

**Comment by michal-gubricky** [comment]
Issue resolved, addressed in related pull requests.
