### ISSUE TITLE
Automatic Setup of Thanos sidecar for Observability of IaaS layer (testbed)

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/issues#481]
As a CSP, I want to observe the state of the IaaS layer running my infrastructure so that I have all the necessary information on fixing broken IaaS (testbed).

Hence, the installation of the Thanos sidecar tool is necessary on the provisioned Infrastructure as a Service (IaaS) to enable the observation and scraping of IaaS metrics.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
For the IaaS layer we use the Prometheus role provided by kolla-ansible to deploy the Prometheus exporters:

https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/prometheus/defaults/main.yml#L23-L125

Additional exporters that are not related to kolla-ansible are part of Ansible collection osism.services. At the moment the only additional exporter there is https://github.com/osism/ansible-collection-services/tree/main/roles/scaphandre (https://github.com/hubblo-org/scaphandre).
