### ISSUE TITLE
There exist Dashboards for IaaS layer health

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/issues#482]
As a CSP, I want see the health of IaaS layer so that I can easily see if there is an incident and can act fast to mitigate an issue.

[See https://github.com/SovereignCloudStack/issues/issues/481#issuecomment-1807688490](https://github.com/SovereignCloudStack/issues/issues/480#issuecomment-1807690673) on how the IaaS layer Grafana dashboards are organized.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by michal-gubricky** [comment]
Issue resolved, addressed in related pull requests.
