### ISSUE TITLE
Optimize build speed

### ISSUE THREAD

**Issue by akafazov** [SovereignCloudStack/issues#484]
Improve SONIC custom image build speed, but only rebuilding the changed component instead of the complete image.

Working document: https://input.scs.community/sonic-built-optimization

**Comment by berendt** [comment]
6 hours is already good ;) In our tests over a year ago, it was significantly longer.

**Comment by akafazov** [comment]
I think we can reduce it alot. The issue is when making multiple changes a day.

**Comment by berendt** [comment]
> I think we can reduce it alot. The issue is when making multiple changes a day.

You should definitely work on it, yes.
