### ISSUE TITLE
Security advisory for intel SA-00950

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#485]
Yet another CPU vuln from intel: https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00950.html
We need to understand, and possibly issue an advisory depending on the outcome of our research.

**Comment by artificial-intelligence** [comment]
more information then in the vendor advisory can be found here:

https://www.openwall.com/lists/oss-security/2023/11/14/7

and especially here:

https://lock.cmpxchg8b.com/reptar.html

Money Quotes:

> We verified this worked even inside an unprivileged guest VM, so this already has serious security implications for cloud providers.

code for reproducers etc. can be found here: https://github.com/google/security-research/tree/master/pocs/cpus/reptar

> We know that we can corrupt the system state badly enough to cause machine check errors, and we’ve also observed threads interfere with execution of processes scheduled on SMT siblings.

> However, we simply don’t know if we can control the corruption precisely enough to achieve privilege escalation. I suspect that it is possible, but we don’t have any way to debug μop execution!

so the impact tl;dr: host dos from unprivileged guest, maybe priv escalation.

**Comment by garloff** [comment]
Very effective DoS.
So, we need to remind our providers to install the microcode updates ...

**Comment by artificial-intelligence** [comment]
I posted via Matrix:

https://matrix.to/#/!xlFjWCAoQenuOeIVQw:matrix.org/$uHJe3OyHydboHlW1KI0tVUqzZ1beQxmgguKDCFAQSkA

I guess a posting to SCS-Tech ML would also be nice? Do we need a blog post as well? That would take more time to prepare though.

**Comment by garloff** [comment]
Fixed by https://github.com/SovereignCloudStack/website/pull/819, published at https://scs.community/2024/01/03/intel-amd-cpu-vulns/
