### ISSUE TITLE
Create ClusterClass template for Openstack

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#492]
As an SCS developer I want to have the ClusterClass for Openstack available as template so I can install this using Helm.

### Definition of Ready
- [ ] Helm folder structure in provider directory exists

### Acceptance Criteria
- [ ] ClusterClass for Openstack exists as template file
- [ ] ClusterClass template can be deployed manually using Helm

We can make use of [prework in k8s-cluster-api-provider](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/template/cluster-template.yaml)

**Comment by mxmxchere** [comment]
I think we are done templating this helm-wise. But we have to do it again with cluster-apis templating mechanism because CSO can not template helmcharts. I will track the progress here: https://github.com/SovereignCloudStack/cluster-stacks/issues/11
