### ISSUE TITLE
SCS Hackathon

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#50]
It has been concluded in the team call on April 21st that it would be nice to have a SCS hackathon.
Whether in presence or online is still tbd.

**Comment by itrich** [comment]
Let's discuss this in the upcoming Community SIG on Wednesday, 2022-05-04.

**Comment by itrich** [comment]
# Results of the first Community SIG Meeting

## SCS Hackathon
- Don't set the scope too narrow. Just let the people gather for 1 – 2 days and see what happens.
- Meet in person somewhere in the middle of Germany (not Berlin!).
- Scheduled for late September.

**Comment by itrich** [comment]
We're currently discussing the sponsoring of a SCS hackathon with some of our partners. More information will follow soon.

**Comment by itrich** [comment]
The SCS Hackathon will take place in Cologne on 2022-11-22. More details will follow soon. Huge thanks to @SovereignCloudStack/plusserver for co-locating and supporting this great opportunity!
