### ISSUE TITLE
[Other] Items to be discussed in Team Ops

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#51]
Items to be discussed in Sprint Planning / Refinement Team Ops (Team 3)

- [x] review of OTC OS Health Monitor presentation from tuesday

**Comment by fkr** [comment]
[ ] Further development of current OS Health Monitor
[ ] OTC Successor OpenStack Health Monitor Date (Andre does not have time tomorrow
[ ] Status Page topic?

**Comment by fkr** [comment]
- [ ] https://github.com/oss-review-toolkit/ort

**Comment by fkr** [comment]
- [ ] VP06d ?

**Comment by fkr** [comment]
- [ ] "User Monitoring" aka. AWS Cloudwatch

**Comment by berendt** [comment]
- https://github.com/prymitive/karma as alternative for Alerta?

**Comment by o-otte** [comment]
- [ ] Status Page -> @master-caster @joshmue 
- [ ] IAM, Use of Machine Identities for Service Authentication -> @joshmue

**Comment by fkr** [comment]
obsoleted by hedgedoc and the meeting preps there
