### ISSUE TITLE
Deployment of status-page-api server to central scs kubernetes cluster

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#511]
In order to test and make use of the prepared deployment techniques in [status-page-deployment](...) deploy the status page api server to the central scs k8s cluster.

## Definition of Done:

- [x] I can send curl requests against the status page api server running on the central scs cluster

**Comment by fkr** [comment]
@jschoone The colleagues from @SovereignCloudStack/gonicus need access to the "Central SCS Kubernetes Cluster". Can you assist here?

**Comment by jschoone** [comment]
> @jschoone The colleagues from @SovereignCloudStack/gonicus need access to the "Central SCS Kubernetes Cluster". Can you assist here?

Yes

**Comment by joshmue** [comment]
Short update:

Got access, thanks @jschoone! Now wondering about the `nip.io` workaround and how to integrate the deployment.

**Comment by joshmue** [comment]
I'll need some domains (A records) to be set up pointing towards the same IP as harbor.

I think about e.g. `dex.status.scs.community` and `api.status.scs.community`.
Maybe just `status.scs.community` would suffice, as well.

@garloff You're still the primary contact about such concerns?

**Comment by garloff** [comment]
Yes, I am.
Normally, I would add CNAME records rather than A records. Or do you intend to distribute this to several IPs soon?

**Comment by joshmue** [comment]
> Or do you intend to distribute this to several IPs soon?

No, I do not think that'll be necessary.

CNAME records should be fine, as well.
That would mean setting up a single A record with multiple CNAME records referring to the A record? Or creating CNAME records referring to the `registry.scs.community` domain? Either way, as long as DNS lookups and LE HTTP-01 challenges work, I'd be good to go to continue.

**Comment by garloff** [comment]
If you need a *subdomain* `status.scs.community` and then several records in it that's possible.
Another option is to have several records in the `scs.community` domain, e.g. `status.scs.community`, `dex-status.scs.community`.

**Comment by joshmue** [comment]
A subdomain with records inside seems optimal (alternatively a wildcard record for the whole subdomain in case there will be more).

All of these options look fine to me for starting off:

- Having a subdomain with A/CNAME records inside
- Having a subdomain with a wildcard entry (so hostname matching happens at the server)
- Having individual `status`/`dex-status` records on the main domain

Having a single A/CNAME record for `status` on the main domain should work as well, but I'd have to setup path-based routing then.

**Comment by fkr** [comment]
@jschoone can you help here now that we moved the dns to artcodix?

**Comment by jschoone** [comment]
> @jschoone can you help here now that we moved the dns to artcodix?

Yes!
@joshmue please ping me via Matrix, then we can configure e.g. ExternalDNS for managing the DNS records

**Comment by joshmue** [comment]
DNS record ready, thanks!

**Comment by joshuai96** [comment]
PR is open for discussion SovereignCloudStack/status-page-deployment/pull/5

**Comment by joshuai96** [comment]
@fkr 

Please try:
```
curl -sL \
https://status.k8s.scs.community/components
```

Further examples can be found [here](https://github.com/SovereignCloudStack/status-page-api/blob/main/docs/example-requests.md).
