### ISSUE TITLE
Extend status-page-deployment with deployment of frontend

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#513]
The status page frontend should be deployed alongside the backend server from the status-page-deployment logic.

## Definition of Ready:

- [ ] https://github.com/SovereignCloudStack/issues/issues/366

## Definition of Done:

- [ ] Frontend container is built and ready
- [ ] Configuration parameters (such as the URL etc.) can be passed into the container
- [ ] Frontend can be accessed through a deployed variant
- [ ] Frontend displays the data accessed through the backend
- [ ] README has been extended accordingly to cover frontend

**Comment by joshmue** [comment]
Did some more testing to make this work also for @snkaupe

**Comment by okautz** [comment]
Current deployment handle API Server, Frontend and depending services for Authentication.
