### ISSUE TITLE
Add Zuul base Jobs to build and push container images to SCS Harbor

### ISSUE THREAD

**Issue by okautz** [SovereignCloudStack/issues#518]
As a SCS contributor, I want to automatically build container images and push them to the SCS Harbor Instance so that Images don't need to be created manually and are ready to use immediately.

For this some base jobs in Zuul should be created that can be used in every repository. Those jobs include:

- build: Job that just builds the image to check if the build process is working, this should be triggered by a PR
- build and push: created on top of "build", to build the container image and push it to a container registry tagged with a commit hash and/or main tag. This should run after a merge to the main branch.
- tag: Just creates a new Tag on the Container Registry accordingly to the created Tag in the Repository

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Creation of base jobs done
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
Here is an example of a build & push job that also handle tags for Zuul.

* https://github.com/osism/python-osism/blob/main/playbooks/pre.yml
* https://github.com/osism/python-osism/blob/main/playbooks/build.yml
* https://github.com/osism/python-osism/blob/main/.zuul.yaml#L32-L53

**Comment by okautz** [comment]
Worked with @joshuai96 using upstream Zuul Jobs/Roles to integrate this to build and push containers for the status-page-api server

**Comment by okautz** [comment]
Done with new instance at https://zuul.sovereignit.cloud with Vault integration
