### ISSUE TITLE
[Other] Items to be discussed in Team Container

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#52]
Items to be discussed in Sprint Planning / Refinement Team Container (Team 2)

- [ ] Vision for IAM and Container-Layer - is there anything aside from this: https://github.com/SovereignCloudStack/Docs/blob/main/Design-Docs/iam_goals.md

**Comment by o-otte** [comment]
- [ ]  Central API #136

**Comment by jschoone** [comment]
Will be closed since one link is no longer available an another is obsoleted by newer concepts.
