### ISSUE TITLE
Prometheus Alertmanager -> Matrix chat reports

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/issues#522]
As an operator, I want to see alerts produced by the https://monitoring.scs.community/ monitoring solution in a dedicated Matrix chat room.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by chess-knight** [comment]
I found alertmanager integrations here https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver, but mentioned matrix integration https://github.com/matrix-org/go-neb is archived and it's spiritual successor https://github.com/matrix-org/matrix-hookshot is too heavy for our needs and probably requires access to the matrix server.
Then, I tried the following projects:
- https://ems-docs.element.io/books/element-cloud-documentation/page/public-slack-bridge
  - it has some limitations, and we also need to manage the slack room
- https://github.com/jaywink/matrix-alertmanager
  - non-configurable templates
- https://github.com/silkeh/alertmanager_matrix
  - we do not need to interact with alertmanager via matrix commands
- https://github.com/metio/matrix-alertmanager-receiver
  - simplest

**Comment by fkr** [comment]
a bit late to the game, but nevertheless I want to comment :)

I very much agree. I've been running goneb for many months now at several places and the successor is indeed way to heavy to 'just route some alertmanager messages'. Am very much fond of the matrix-alertmanager-receiver you've found!
