### ISSUE TITLE
Prepare summary of technological approaches for E2E encryption between customers workloads

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/issues#536]
From the result of https://github.com/SovereignCloudStack/issues/issues/532

As an SCS Developer, I want a comprehensive summary of proposed options to tackle given attack vectors to decide on the best one.

Considered approaches:

- Encryption directly on the networking stack using VXLAN or Geneve
- Using a custom eBPF-based solution
- Deploying Cilium agents

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by MatusJenca2** [comment]
Research/summary will be tracked [here](https://input.scs.community/8Y24WfcKQaaVEkuQm9imQQ#)

**Comment by fdobrovolny** [comment]
Closed in favor of #675
