### ISSUE TITLE
markdown documentation for hackaton 

### ISSUE THREAD

**Issue by piobig2871** [SovereignCloudStack/issues#546]
I want markdown documentation for the team to establish first step in the project and have general understand what is reuiered for the fork.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined and documented

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by Erik-Kostelansky-dNation** [comment]
Issue has been implemented and merged into main
