### ISSUE TITLE
logger class 

### ISSUE THREAD

**Issue by piobig2871** [SovereignCloudStack/issues#547]
I want logger class to collect steps and informations.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined and documented 
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fraugabel** [comment]
i added the default logger class int now has to be imported and integrated in the working skripts to log steps and other data
