### ISSUE TITLE
VMWare migration 

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#557]
An epic that collects all vmware migration related user stories.

- [x] #560 
- [x] #558 
- [ ] #559

Use-cases:

- As someone who is stuck with vmware, I want to get a fair understanding of what is involved (eg. necessary steps) in order to move my workload to a different offering (=> SCS-compliant) while also understanding the consequences (downtime) of that

- As a company that has a vmware esxi in their server room, I want to migrate the workloads that are running on the esxi into an existing SCS-compliant cloud.

- As a company that has workloads running on an vmware installation, I want to migrate the workloads (as automated as possible) onto an existing SCS-compliant cloud.

**Comment by Belgeron** [comment]
Testing: https://github.com/vexxhost/migratekit 

We setup a Docker Server, and tried to Migrate Hosts from ESXi 7.0(U1) or older ESXi 6.5 with free Licenses to Openstack.
Problem is that it seems even the documentions stated it is working with ESXi the free license has not the feature enabled needed.

- Connection to ESXi is working
- Finding the correct VMware is also working
- Starting the 1st Migration process - stopping with an error message.

`Error: ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.`

We have no ESXi 8.x or VCenter Systems running where we could futher test the script, but this problem will hit anybody who tries to move his old ESXi Free Licensed Host to Openstack with that mirgation Docker Container, this is more suitable for larger environments.

I tried to replace the 8.0.x VDDK with a 7.0(U1) VDDK if his was the problem, still the same Error Message from the Server.

I also opened an Issue asking for more information about supported releases, needed licenses or features enabled.
https://github.com/vexxhost/migratekit/issues/7

**Comment by Belgeron** [comment]
My opened issue was processed and answered, the documentation was also extended by a point that it does not work with the free version, because API interfaces are missing here.

https://github.com/vexxhost/migratekit/issues/7

We are unable to carry out a further in-depth technical test as a result.
