### ISSUE TITLE
Setting up prometheus and pushgateway locally 

### ISSUE THREAD

**Issue by piobig2871** [SovereignCloudStack/issues#573]
I want to have a described process of setting up prometheus and pushgateway so that rest of a team will have a full knowledge how to set it up. Please collect the logs for future work with the data

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by Erik-Kostelansky-dNation** [comment]
Fixed in this [PR](https://github.com/SovereignCloudStack/scs-health-monitor/pull/27) and [PR](https://github.com/SovereignCloudStack/scs-health-monitor/pull/28)
