### ISSUE TITLE
Grafana charts creation

### ISSUE THREAD

**Issue by piobig2871** [SovereignCloudStack/issues#577]
I wantto have a grafana charts for our tests so that the logs from prometheus will be presented.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fraugabel** [comment]
grafana dashboard created
