### ISSUE TITLE
Mapping floating ips

### ISSUE THREAD

**Issue by piobig2871** [SovereignCloudStack/issues#594]
I want to have mapped in the test creating and deleting floating ips so that it can be performed automatically.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by piobig2871** [comment]
resolved on https://github.com/SovereignCloudStack/scs-health-monitor/pull/38

**Comment by fraugabel** [comment]
done
