### ISSUE TITLE
Integrate status-page documentation into docs.scs.community

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#610]
As a operator it is really convenient for me to have all SCS related docs in one place. This place is docs.scs.community and as such it would be really good to have the documentation related to the status page present there as well.

Initially this refers primarily to the deployment documentation. The documentation within the corresponding repos should be done in a way that it can be pulled into docs.scs.community.

Refer to this part of the documentation that explains the process: https://docs.scs.community/community/contribute/adding-docs-guide

## Definition of Ready:

- [x] Documentation within the repositories is written

## Definition of Done:
- [x] Deployment Documentation is being included
- [x] Documentation of the API server is being included
- [x] [Example-Requests are present](https://github.com/SovereignCloudStack/status-page-api/blob/main/docs/example-requests.md)
- [x] Documentation is being pulled into docs.scs.community

**Comment by joshuai96** [comment]
SovereignCloudStack/status-page-web#19 will be excluded at first.
