### ISSUE TITLE
Setup OVN with OVN exporter on a single node

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#63]
Setup OVN with OVN exporter on a single node.

Expected outcome:

- Gather insights to write ansible playbook for provisioning
- Documentation of OVN exporter

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] I have a understanding of how to write the playbook for provisioning
- [x] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by matfechner** [comment]
Done and understand how ovn-exporter interact  with ovn .
One open challenge is reduce duplicated data's, one possible way is evaluate with prometheus relabling rules in a follow. up story
