### ISSUE TITLE
Write playbook for provisioning of OVN exporter

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#64]
Based on the insights of #63, write a playbook for provisioning OVN exporter.
This needs to include proper relabeling of the prometheus metrics in order to deduplicate metrics coming from the HA setup. 

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] I have a playbook for provisioning OVN exporter
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by matfechner** [comment]
After release container based  ovn-exporter
[x] playbook is writen
[x] testing in testbed

**Comment by tibeer** [comment]
https://review.opendev.org/c/openstack/kolla-ansible/+/855498

**Comment by matfechner** [comment]
Reworked an tested  will upload  patchset end of this week

**Comment by matfechner** [comment]
Some trouble to  run it inside container:

https://github.com/greenpau/ovn_exporter/issues/11

**Comment by fkr** [comment]
Blocked because of upstream acceptence.
