### ISSUE TITLE
Implement metrics in status-page-api

### ISSUE THREAD

**Issue by joshuai96** [SovereignCloudStack/issues#655]
## Definition of Ready:

- [x] Done research to instrument `status-page-api`
- [x] Define important metrics to get
- [x] Implement metrics

## Definition of Done:

- [x] `status-page-api` provides a metrics endpoint

**Comment by matofeder** [comment]
It seems that status-page API integrates `echo` Go web framework. 
It is possible to integrate prometheus middleware https://echo.labstack.com/docs/middleware/prometheus .
It generates metrics for HTTP requests and allows to create also custom ones.

**Comment by joshuai96** [comment]
@matofeder Thats very good, as the OpenTelemetry `echo` auto instrumentation does not seem to provide metrics, only traces.

**Comment by joshuai96** [comment]
Using the prometheus middleware from echo provides good default metrics for an API server. This was added in 
SovereignCloudStack/status-page-api#27
