### ISSUE TITLE
Internal or manual conformance tests and audits at CSP side

### ISSUE THREAD

**Issue by markus-hentsch** [SovereignCloudStack/issues#668]
More recent SCS standards which go beyond simple user-facing aspects of an SCS infrastructure create an increasing demand for a standardized approach for executing internal and/or manual conformance tests and audits in the infrastructure directly.
This is necessary for test and audit scenarios where the information is not accessible from the outside (e.g. via API) and/or requires admin privileges.

This issue should serve as a starting point to establish such a process as well as keeping track of applicable standards.

The exact implementation is up for debate. So far there have been some ideas about test scripts that can be executed by a CSP admin and generate a report file which can be submitted to some SCS service. Challenges arise when the tests need to go deep into the infrastructure (e.g. checking the config file entries of every Neutron agent) and infrastructures may differ greatly in their architecture between CSPs making it hard to create a one-size-fits-all script for verification.

### Applicable Standards

The standards which currently have limited conformance test capabilities due to the lack of CSP-side audit possibilites will be tracked here:

- [volume backup functionality](https://github.com/SovereignCloudStack/standards/pull/567)
  - check that Cinder Backup is configured to a separate storage backend different from the volume storage backend
- [secure connections](https://github.com/SovereignCloudStack/standards/pull/548)
  - check that RPC and DB channels are encrypted
  - check that internal API channels are encrypted
  - assess libvirt interface and Nova live migration security
  - assess Neutron network security
- [tenant VM DNS](https://github.com/SovereignCloudStack/standards/pull/570)
  - check mandated Neutron server & agent config values related to DNS
- [Domain Manager](https://github.com/SovereignCloudStack/standards/pull/343)
  - test preparation requires cloud admin rights (creating domain-manager users)

**Comment by mbuechse** [comment]
Should this replace https://github.com/SovereignCloudStack/standards/issues/611 ?

**Comment by markus-hentsch** [comment]
> Should this replace [SovereignCloudStack/standards#611](https://github.com/SovereignCloudStack/standards/issues/611) ?

I think we only should keep one of them. Either close yours as duplicate or transfer this one's description over. Essentially it boils down to whether we want this issue in the issues or the standards repo.

**Comment by mbuechse** [comment]
Good point, I hadn't realized that the repositories were different. I do prefer the standards repo by quite some margin. So I think we should transfer the description.

**Comment by markus-hentsch** [comment]
As discussed with @mbuechse, transferred title and description over to https://github.com/SovereignCloudStack/standards/issues/611 and closing this as duplicate.
