### ISSUE TITLE
July 2024 release of Status Page and API - containerized application ready for deployment

### ISSUE THREAD

**Issue by bitkeks** [SovereignCloudStack/issues#673]
As discussed in [ops call 2024-06-27](https://input.scs.community/2024-scs-team-ops?both#Status-Page-and-API-MVP-bitkeks), the release for this tech preview (was called "MVP") is scheduled for **Thursday, July 18th 2024**.

The tech preview contains a deliverable, containerized application with front-end UI and back-end API. Every CSP should be able to take the container (or the two containers) and deploy them, resulting in an API to send events to and a front-end, displaying these.

The “planned maintenance” feature is not included in this MVP, but will be worked on after.

## Definition of Ready
- [x] #369

**Comment by snkaupe** [comment]
#369 is the main issue related to this ticket. Further issues concerning the API server *might* be created in the near future, pending some discussions on the exact behaviour of the API server upon receiving a delete request.

**Comment by bitkeks** [comment]
Please link any work that is done for this issue here.

**Comment by joshuai96** [comment]
Monitoring has been marked as done, as https://monitoring.scs.community/ now includes the status page metrics.

**Comment by bitkeks** [comment]
Please mark this one as done when status page is released for R7

Reference to component names for SCS demo purposes: https://github.com/SovereignCloudStack/issues/issues/613

**Comment by joshuai96** [comment]
This can be closed as the release has been made.
