### ISSUE TITLE
July 2024 release of Central API as containerized application

### ISSUE THREAD

**Issue by bitkeks** [SovereignCloudStack/issues#674]
As discussed in [ops call 2024-06-27](https://input.scs.community/2024-scs-team-ops?both#Central-API-MVP-joshmue-bitkeks), we schedule a release for Central API **for Tuesday, July 30th 2024**. 

This release aims to produce a deployment-ready application. 

It includes:
* A repo with documentation about deployment and configuration,
* a containerized Crossplane app with Central API definitions and 
* a way to deploy this instance. 

Running the instance and configuring my backends then allows me to send requests for VMs, networks and k8s clusters to Crossplane, which abstracts the backend calls away from the user.

For IaaS, OpenStack can be utilized. As Kubernetes backends, Cluster API (SCS Cluster Stacks) and Gardener are supported. All backends were successfully tested (at Hackathon and in last SIG meeting).

Now it all has to be packaged so CSPs can deploy the Central API component for testing and evaluation. 

@mxmxchere I added you as assignee because you also have a lot of knowledge, please sync with @joshmue

Please also review #364 and update/close where possible.

**Comment by bitkeks** [comment]
To CSPs and container team, your feedback and involvement is very welcome!

@frosty-geek 
@berendt 
@artificial-intelligence 
@jschoone

**Comment by bitkeks** [comment]
Please link any current work to this issue. PRs, discussions..

**Comment by joshmue** [comment]
- #665 is mainly being implemented by SovereignCloudStack/central-api#15
- As @frosty-geek suggested, I contacted @scoopex about a test/demo deployment on the SCS installation for the SCS project; As soon this env is ready for that, we can deploy the results of #665 there

**Comment by bitkeks** [comment]
Blog post discussed today in SIG Central API meeting: https://github.com/SovereignCloudStack/website/pull/990

**Comment by bitkeks** [comment]
Done
