### ISSUE TITLE
Prepare a decision record and document all findings about Node to Node encryption

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/issues#675]
As an SCS Developer, I want to compile the results so far of epic #531 into a decision record.

This will probably result in a draft outlining the current state and lessons learned and should be revisited in time and fully completed once there are actual PRs to upstream.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by OgarOgarovic** [comment]
[PR here](https://github.com/SovereignCloudStack/standards/pull/655)
