### ISSUE TITLE
Resolve floating IP allocation

### ISSUE THREAD

**Issue by piobig2871** [SovereignCloudStack/issues#677]
there is a problem with allocation floating ip. We take it from the pool and not creeating new one. 

TODO:
disable funcionality as it is
create a function to create floating ip
test the changes

**Comment by tsmado** [comment]
Floating IP handling has been updated to not take available FIPs from the pool, but rather create new ones for the purpose of testing. These newly created FIPs are then cleaned after every test run or in case of any test failure.
