### ISSUE TITLE
Towards gitops cluster management

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#68]
As a KaaS provider, I want to define and offer an easy to manage set of parameters that DevOps teams can use to create/control/lifecycle-manage clusters that work across multiple clouds with relatively little customization.

Layering:
1. Naked cluster incl. CCM
2. Storage, networking
3. ingress, cert-manager, ...
4. logging, tracing
5. Platform services / middleware (databases, ...)
6. service/application deployment

(Layers 1 -- 3 are covered by current SCS R2.)
Mechanisms should be capable of all 6, but we may only standardize 1 ... 3 (and later 4, 5???)

Split of responsibility between provider and user (DevOps team). Lower layers are more strongly dependent on provider specifics than higher layers. Huge amounts of defaults ... -> need to be delivered by providers

[As a DevOps team, I want to define clusters that get created by the platform, so that I can have environments for development, testing and production for my applications/services.]

Deliverables:
- Example configuration (with all options and a short description)
- Documentation

Parameters fall into several categories:
1. Provider-independent
7. [Provider-abstractable]??
8. Provider dependent (defaults provided from provider should not require touching this from the DevOps team for simple cases) 

TODO:
- Investigate helmfile mechanism
- Review parameter sets values.yaml (SCS, gridscale, Gardener: shoot resource manifest, syself/Hetzner, GiantSwarm, C&H, ...)

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
@jschoone this is a very old issue and originates from long before KaaS V2. Is this something still relevant and should stay around as an issue?

**Comment by jschoone** [comment]
@fkr no I'll close this. Can be reopened if needed.
