### ISSUE TITLE
Prepare the infrastructure repository

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/issues#7]
* Harbor registry with Object Storage backend + Postgres (optional)
* Keycloak service as identity backend

**Comment by tibeer** [comment]
@joshmue correct me if I'm wrong but the registry is already running, right?
What about Keycloak?

**Comment by joshmue** [comment]
@tibeer Yes, Harbor is deployed at https://registry.scs.community/ from the k8s-harbor repo.

**Comment by tibeer** [comment]
@joshmue and keycloak?

**Comment by joshmue** [comment]
@tibeer I don't know if it uses keycloak, but the instance uses https://scs.sovereignit.de as OIDC provider.

**Comment by tibeer** [comment]
@berendt I guess this can be closed than?
