### ISSUE TITLE
calculate and push totDur Benchmark

### ISSUE THREAD

**Issue by piobig2871** [SovereignCloudStack/issues#701]
Benchmark-Metric that should be tracked in the Grafana dashboard

**Comment by fraugabel** [comment]
totDur- duration timer created in in before all and calculated in after all -> returns metric of total duration for one or more feature runs. done 
still ToDo: pushingMetric to Prometheus/Grafana

**Comment by piobig2871** [comment]
pushingMetric to Prometheus/Grafana was completed on another branch
