### ISSUE TITLE
Cluster Settings for Gridscale

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#76]
As a SCS KaaS Dev, I want ot have an overview over the Gridscale container cluster settings.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
This issue is marked 'done', but is in state 'open'. @garloff?
