### ISSUE TITLE
KaaS settings overview for Hetzner

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#77]
As SCS KaaS Dev, I want to get an overview over the Hetzer / CAPH cluster settings.

See Epic #74.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
This issue is marked 'done', but is in state 'open'. @garloff?
