### ISSUE TITLE
Re-Created user in IDP causes NullPointerException in Keycloak

### ISSUE THREAD

**Issue by Ferenc-** [SovereignCloudStack/issues#9]
A known issue to be aware of is [KEYCLOAK-16095](https://issues.redhat.com/browse/KEYCLOAK-16095?focusedCommentId=16374384&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16374384).

This also means that tests in SCS that [create a user in IDP](https://github.com/osism/testbed/blob/main/terraform/integration-tests/tests/new_user.robot#L21), can't be exactly repeated with the same user without a workaround,
as it would hit the user re-creation issue.
Perhaps a workaround should be prioritised, but as of now, the manual synchronisation functionality in Keycloak also appears to be unreliable.

**Comment by fkr** [comment]
@JuanPTM @reqa is this issue still present?
