### ISSUE TITLE
[testbed] Migration of CI jobs from github action to zuul

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#91]

**Comment by fkr** [comment]
https://github.com/osism/testbed/pull/1240

**Comment by garloff** [comment]
This is a multi-sprint activity.
- docs jobs
- lint jobs
have been done.

**Comment by fkr** [comment]
Open Question: will this be finished within R3 or will this take longer than that?

**Comment by berendt** [comment]
* deploy test moved
* upgrade test moved
* periodic deploy test (betacloud) moved
* periodic upgrade test (betacloud) will be added tomorrow
* linters moved
* documentation moved

Still open: daily deployments @ OTC, Cleura & PCO (will be finished before R3)

**Comment by itrich** [comment]
@matfechner will discuss this pending item with @SovereignCloudStack/osism team

**Comment by fkr** [comment]
Only daily jobs missing.

**Comment by fkr** [comment]
Daily jobs have been moved for OTC, cleura, PCO and Wavestack.
Due to an outage yesterday the Zuul is currently broken. 
@berendt @osfrickler please link the OSISM Issue here.

**Comment by osfrickler** [comment]
https://github.com/osism/issues/issues/349

**Comment by osfrickler** [comment]
Completed by https://github.com/osism/testbed/pull/1391
