### ISSUE TITLE
Evaluate ORT - OSS-Review-Toolkit

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#94]
The ORT (OSS-Review-Toolkit) looks very interesting in the scope of analyzing OSS.

https://github.com/oss-review-toolkit/ort

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [ ] Documentation has been updated
- [x] Release Notes have been updated

**Comment by fkr** [comment]
Imho the evaluation has been finished. @itrich you agree?

**Comment by itrich** [comment]
Right. @joshmue did a great job and provided a good starting point to adapt the pipeline to other repositories. Thank you!
