### ISSUE TITLE
Architecture overview of federated auth within SCS

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#96]
As a SCS developer / operator we need to have a clear understanding of how the federated auth works and which components are involved when and how. An architecture overview will help to grow this understanding.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by garloff** [comment]
Will use two testbeds to work on this in next SIG IAM meetings.

**Comment by garloff** [comment]
No progress

**Comment by reqa** [comment]
Status: We have two testbeds, but:
1. they don't seem to be deployed properly as there is no keystone container running on the nodes in both deployments
2. the certificate used by keycloak is expired https://github.com/osism/testbed/issues/1296
3. My [pull request against osism for adding oauth2 support to keystone](https://github.com/osism/container-image-kolla-ansible/pull/224) has been closed on May 10, leaving https://github.com/osism/issues/issues/130 stalled. This way, we have to hack all of it again into each keystone of each testbed.
4. We can only have confidence with the intended architecture if we manage to find out (during a hack session), if our approach to federation (keystone -> keycloak -> keycloak-remote) actually works with openstack-cli, what is missing there and if it will be possible to implement, maintain and/or upstream the changes.

**Comment by fkr** [comment]
@reqa opened this PR: https://github.com/SovereignCloudStack/Docs/pull/113 
We've agreed in this weeks Team OPS & IAM meeting that the PR will be opened and further work on this is done within the PR. 
thanks @reqa. 
For the discussion from thursday, please check [these minutes](https://github.com/SovereignCloudStack/minutes/blob/main/ops-iam/20220908.md)

**Comment by fkr** [comment]
Imho this should be closed, since we have an initial overview. @reqa agree?

**Comment by reqa** [comment]
It moved here: https://github.com/SovereignCloudStack/standards/tree/main/Design-Docs/IAM-federation
